// Auto-generated by @gqlens/codegen
// Sections: typed nodes, schema contract, runtime entrypoints, selectors, mutation API.
import { useGQLensSession, useLiveGQLensSession, type QueryConfig as GQLensQueryConfig } from "@gqlens/react";
import {
  bindSelection as bindGQLensSelection,
  createAccessorNode,
  defineInvalidation as defineGQLensInvalidation,
  defineSelection as defineGQLensSelection,
  type AccessorContext,
  type GQLensSchemaContract,
} from "@gqlens/core/codegen";
import type {
  GraphDataInvalidation,
  EntityRef,
  MutationOperation,
  PreparedSelection,
  VariablePlaceholder,
} from "@gqlens/core";
import type * as Types from "./types";

type GQLensArgValue<T> =
  T extends readonly (infer Item)[]
    ? readonly GQLensArgValue<Item>[] | VariablePlaceholder
    : T extends object
      ? { readonly [Key in keyof T]: GQLensArgValue<T[Key]> } | VariablePlaceholder
      : T | VariablePlaceholder;
type GQLensArgs<T> = { readonly [Key in keyof T]: GQLensArgValue<T[Key]> };
type GQLensQueryOptions = Omit<GQLensQueryConfig, "schema">;

// Typed accessor nodes
export interface NodeNode {
  readonly __typename: string | undefined;
  readonly id: Types.Node["id"] | undefined;
  readonly $on: {
    readonly User: UserNode;
    readonly Post: PostNode;
  };
}

export interface UserNode {
  readonly __typename: string | undefined;
  readonly id: Types.User["id"] | undefined;
  readonly name: Types.User["name"] | undefined;
  readonly avatar: Types.User["avatar"] | undefined;
  readonly online: Types.User["online"] | undefined;
  readonly posts: { readonly ids: readonly string[] | undefined };
}

export interface PostNode {
  readonly __typename: string | undefined;
  readonly id: Types.Post["id"] | undefined;
  readonly title: Types.Post["title"] | undefined;
  readonly content: Types.Post["content"] | undefined;
  readonly tags: Types.Post["tags"] | undefined;
  readonly author: UserNode;
  readonly comments: { readonly ids: readonly string[] | undefined };
}

export interface CommentNode {
  readonly __typename: string | undefined;
  readonly id: Types.Comment["id"] | undefined;
  readonly body: Types.Comment["body"] | undefined;
  readonly author: UserNode;
}

export interface PetNode {
  readonly __typename: string | undefined;
  readonly id: Types.Pet["id"] | undefined;
  readonly name: Types.Pet["name"] | undefined;
  readonly $on: {
    readonly Cat: CatNode;
    readonly Dog: DogNode;
  };
}

export interface CatNode {
  readonly __typename: string | undefined;
  readonly id: Types.Cat["id"] | undefined;
  readonly name: Types.Cat["name"] | undefined;
  readonly meows: Types.Cat["meows"] | undefined;
}

export interface DogNode {
  readonly __typename: string | undefined;
  readonly id: Types.Dog["id"] | undefined;
  readonly name: Types.Dog["name"] | undefined;
  readonly barks: Types.Dog["barks"] | undefined;
}

export interface SearchResultNode {
  readonly __typename: string | undefined;
  readonly $on: {
    readonly User: UserNode;
    readonly Post: PostNode;
    readonly Node: NodeNode;
  };
}

export interface QueryNode {
  readonly __typename: string | undefined;
  readonly user: (args: GQLensArgs<Types.QueryUserArgs>) => UserNode;
  readonly viewer: UserNode;
  readonly post: (args: GQLensArgs<Types.QueryPostArgs>) => PostNode;
  readonly posts: (args?: GQLensArgs<Types.QueryPostsArgs>) => { readonly ids: readonly string[] | undefined };
  readonly pet: (args: GQLensArgs<Types.QueryPetArgs>) => PetNode;
  readonly search: (args: GQLensArgs<Types.QuerySearchArgs>) => { readonly refs: readonly EntityRef[] | undefined };
}

// Schema contract consumed by @gqlens/core
export const gqlensSchema: GQLensSchemaContract = {
  query: {
    type: "Query",
    kind: "root",
    fields: {
      "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
      "user": { name: "user", result: { "kind": "object", "cardinality": "one", "typeName": "User", "objectKind": "entity" }, args: { "id": "ID!" } },
      "viewer": { name: "viewer", result: { "kind": "object", "cardinality": "one", "typeName": "User", "objectKind": "entity" } },
      "post": { name: "post", result: { "kind": "object", "cardinality": "one", "typeName": "Post", "objectKind": "entity" }, args: { "id": "ID!" } },
      "posts": { name: "posts", result: { "kind": "object", "cardinality": "list", "typeName": "Post", "objectKind": "entity" }, args: { "first": "Int", "done": "Boolean" } },
      "pet": { name: "pet", result: { "kind": "object", "cardinality": "one", "typeName": "Pet", "objectKind": "entity", "isAbstract": true, "possibleTypes": ["Cat","Dog"] }, args: { "id": "ID!" } },
      "search": { name: "search", result: { "kind": "object", "cardinality": "list", "typeName": "SearchResult", "objectKind": "entity", "isAbstract": true, "possibleTypes": ["User","Post"] }, args: { "text": "String!" } },
    },
  },
  mutation: {
    type: "Mutation",
    kind: "root",
    fields: {
      "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
      "renameUser": { name: "renameUser", result: { "kind": "object", "cardinality": "one", "typeName": "User", "objectKind": "entity" }, args: { "id": "ID!", "name": "String!" } },
      "addComment": { name: "addComment", result: { "kind": "object", "cardinality": "one", "typeName": "Comment", "objectKind": "entity" }, args: { "postId": "ID!", "content": "String!" } },
    },
  },
  objects: {
    "Node": {
      type: "Node",
      kind: "entity",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "id": { name: "id", result: { "kind": "scalar", "cardinality": "one" } },
      },
      isAbstract: true,
      possibleTypes: ["User","Post"],
      typeConditions: ["User","Post"],
    },
    "User": {
      type: "User",
      kind: "entity",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "id": { name: "id", result: { "kind": "scalar", "cardinality": "one" } },
        "name": { name: "name", result: { "kind": "scalar", "cardinality": "one" } },
        "avatar": { name: "avatar", result: { "kind": "scalar", "cardinality": "one" } },
        "online": { name: "online", result: { "kind": "scalar", "cardinality": "one" } },
        "posts": { name: "posts", result: { "kind": "object", "cardinality": "list", "typeName": "Post", "objectKind": "entity" } },
      },
    },
    "Post": {
      type: "Post",
      kind: "entity",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "id": { name: "id", result: { "kind": "scalar", "cardinality": "one" } },
        "title": { name: "title", result: { "kind": "scalar", "cardinality": "one" } },
        "content": { name: "content", result: { "kind": "scalar", "cardinality": "one" } },
        "tags": { name: "tags", result: { "kind": "scalar", "cardinality": "list" } },
        "author": { name: "author", result: { "kind": "object", "cardinality": "one", "typeName": "User", "objectKind": "entity" } },
        "comments": { name: "comments", result: { "kind": "object", "cardinality": "list", "typeName": "Comment", "objectKind": "entity" } },
      },
    },
    "Comment": {
      type: "Comment",
      kind: "entity",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "id": { name: "id", result: { "kind": "scalar", "cardinality": "one" } },
        "body": { name: "body", result: { "kind": "scalar", "cardinality": "one" } },
        "author": { name: "author", result: { "kind": "object", "cardinality": "one", "typeName": "User", "objectKind": "entity" } },
      },
    },
    "Pet": {
      type: "Pet",
      kind: "entity",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "id": { name: "id", result: { "kind": "scalar", "cardinality": "one" } },
        "name": { name: "name", result: { "kind": "scalar", "cardinality": "one" } },
      },
      isAbstract: true,
      possibleTypes: ["Cat","Dog"],
      typeConditions: ["Cat","Dog"],
    },
    "Cat": {
      type: "Cat",
      kind: "entity",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "id": { name: "id", result: { "kind": "scalar", "cardinality": "one" } },
        "name": { name: "name", result: { "kind": "scalar", "cardinality": "one" } },
        "meows": { name: "meows", result: { "kind": "scalar", "cardinality": "one" } },
      },
    },
    "Dog": {
      type: "Dog",
      kind: "entity",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "id": { name: "id", result: { "kind": "scalar", "cardinality": "one" } },
        "name": { name: "name", result: { "kind": "scalar", "cardinality": "one" } },
        "barks": { name: "barks", result: { "kind": "scalar", "cardinality": "one" } },
      },
    },
    "SearchResult": {
      type: "SearchResult",
      kind: "entity",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
      },
      isAbstract: true,
      possibleTypes: ["User","Post"],
      typeConditions: ["User","Post","Node"],
    },
  },
};

// useQuery runtime entrypoint
export function useQuery(config?: GQLensQueryOptions): QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void } {
  const state = useGQLensSession({ ...config, schema: gqlensSchema });
  const ctx: AccessorContext = {
    root: "Query",
    store: state.store,
    demand: (steps) => state.demand("Query", steps),
    read: state.read,
  };
  const accessor = createAccessorNode<QueryNode>(ctx, gqlensSchema, gqlensSchema.query) as QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void };
  Object.defineProperties(accessor, {
    loading: { enumerable: true, get: () => state.loading },
    error: { enumerable: true, get: () => state.error },
    refetch: { enumerable: true, value: () => state.session.refetch() },
  });
  return accessor;
}

// useLiveQuery runtime entrypoint
export function useLiveQuery(config?: GQLensQueryOptions): QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void } {
  const state = useLiveGQLensSession({ ...config, schema: gqlensSchema });
  const ctx: AccessorContext = {
    root: "Query",
    store: state.store,
    demand: (steps) => state.demand("Query", steps),
    read: state.read,
  };
  const accessor = createAccessorNode<QueryNode>(ctx, gqlensSchema, gqlensSchema.query) as QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void };
  Object.defineProperties(accessor, {
    loading: { enumerable: true, get: () => state.loading },
    error: { enumerable: true, get: () => state.error },
    refetch: { enumerable: true, value: () => state.session.refetch() },
  });
  return accessor;
}

// usePreparedQuery prepared runtime entrypoint
export function usePreparedQuery(selection: PreparedSelection, variables: Readonly<Record<string, unknown>>, config?: GQLensQueryOptions): QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void } {
  const state = useGQLensSession({ ...config, schema: gqlensSchema });
  for (const path of bindGQLensSelection(selection, variables)) {
    state.demand(path.root, path.steps);
  }
  const ctx: AccessorContext = {
    root: "Query",
    store: state.store,
    demand: (steps) => state.demand("Query", steps),
    read: state.read,
  };
  const accessor = createAccessorNode<QueryNode>(ctx, gqlensSchema, gqlensSchema.query) as QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void };
  Object.defineProperties(accessor, {
    loading: { enumerable: true, get: () => state.loading },
    error: { enumerable: true, get: () => state.error },
    refetch: { enumerable: true, value: () => state.session.refetch() },
  });
  return accessor;
}

// Static selector builders
export function defineSelection(callback: (q: QueryNode, v: (name: string) => VariablePlaceholder) => void): PreparedSelection {
  return defineGQLensSelection<QueryNode>(gqlensSchema, gqlensSchema.query, callback);
}

export function defineInvalidation(callback: (q: QueryNode) => unknown): GraphDataInvalidation {
  return defineGQLensInvalidation<QueryNode>(gqlensSchema, gqlensSchema.query, callback);
}

// Mutation operation descriptors
export const api: {
  readonly comment: {
    readonly add: MutationOperation<Types.MutationAddCommentArgs, Pick<NonNullable<Types.Mutation["addComment"]>, "id" | "__typename" | "body">>;
  };
  readonly user: {
    readonly rename: MutationOperation<Types.MutationRenameUserArgs, Pick<NonNullable<Types.Mutation["renameUser"]>, "id" | "__typename" | "name" | "avatar" | "online">>;
  };
} = {
  comment: {
    add: {
      operationName: "addComment",
      query: "mutation addComment($postId: ID!, $content: String!) { addComment(postId: $postId, content: $content) { id __typename body } }",
      schema: gqlensSchema,
      variables: (input: Types.MutationAddCommentArgs): Record<string, unknown> => ({
        postId: input.postId,
        content: input.content,
      }),
    },
  },
  user: {
    rename: {
      operationName: "renameUser",
      query: "mutation renameUser($id: ID!, $name: String!) { renameUser(id: $id, name: $name) { id __typename name avatar online } }",
      schema: gqlensSchema,
      variables: (input: Types.MutationRenameUserArgs): Record<string, unknown> => ({
        id: input.id,
        name: input.name,
      }),
    },
  },
};
