// Auto-generated by @gqlens/codegen
// Sections: typed nodes, schema metadata, runtime entrypoints, selectors, mutation API.
import { useGQLensSession, useLiveGQLensSession } from "@gqlens/react";
import {
  createAccessorNode,
  defineInvalidation as defineGQLensInvalidation,
  defineSelection as defineGQLensSelection,
  type AccessorContext,
  type SchemaMeta,
} from "@gqlens/core/codegen";
import type {
  EntityRef,
  InvalidationTarget,
  MutationOperation,
  PreparedSelection,
  QuerySessionConfig,
  VariablePlaceholder,
} from "@gqlens/core";
import type * as Types from "./types";

type GQLensArgValue<T> =
  T extends readonly (infer Item)[]
    ? readonly GQLensArgValue<Item>[] | VariablePlaceholder
    : T extends object
      ? { readonly [Key in keyof T]: GQLensArgValue<T[Key]> } | VariablePlaceholder
      : T | VariablePlaceholder;
type GQLensArgs<T> = { readonly [Key in keyof T]: GQLensArgValue<T[Key]> };

// Typed accessor nodes
export interface NodeNode {
  readonly __typename: string | undefined;
  readonly id: Types.Node["id"] | undefined;
  readonly $on: {
    readonly User: UserNode;
    readonly Post: PostNode;
  };
}

export interface UserNode {
  readonly __typename: string | undefined;
  readonly id: Types.User["id"] | undefined;
  readonly name: Types.User["name"] | undefined;
  readonly avatar: Types.User["avatar"] | undefined;
  readonly online: Types.User["online"] | undefined;
  readonly posts: { readonly ids: readonly string[] | undefined };
}

export interface PostNode {
  readonly __typename: string | undefined;
  readonly id: Types.Post["id"] | undefined;
  readonly title: Types.Post["title"] | undefined;
  readonly content: Types.Post["content"] | undefined;
  readonly tags: Types.Post["tags"] | undefined;
  readonly author: UserNode;
  readonly comments: { readonly ids: readonly string[] | undefined };
}

export interface CommentNode {
  readonly __typename: string | undefined;
  readonly id: Types.Comment["id"] | undefined;
  readonly body: Types.Comment["body"] | undefined;
  readonly author: UserNode;
}

export interface PetNode {
  readonly __typename: string | undefined;
  readonly id: Types.Pet["id"] | undefined;
  readonly name: Types.Pet["name"] | undefined;
  readonly $on: {
    readonly Cat: CatNode;
    readonly Dog: DogNode;
  };
}

export interface CatNode {
  readonly __typename: string | undefined;
  readonly id: Types.Cat["id"] | undefined;
  readonly name: Types.Cat["name"] | undefined;
  readonly meows: Types.Cat["meows"] | undefined;
}

export interface DogNode {
  readonly __typename: string | undefined;
  readonly id: Types.Dog["id"] | undefined;
  readonly name: Types.Dog["name"] | undefined;
  readonly barks: Types.Dog["barks"] | undefined;
}

export interface SearchResultNode {
  readonly __typename: string | undefined;
  readonly $on: {
    readonly User: UserNode;
    readonly Post: PostNode;
    readonly Node: NodeNode;
  };
}

export interface QueryNode {
  readonly __typename: string | undefined;
  readonly user: (args: GQLensArgs<Types.QueryUserArgs>) => UserNode;
  readonly viewer: UserNode;
  readonly post: (args: GQLensArgs<Types.QueryPostArgs>) => PostNode;
  readonly posts: (args?: GQLensArgs<Types.QueryPostsArgs>) => { readonly ids: readonly string[] | undefined };
  readonly pet: (args: GQLensArgs<Types.QueryPetArgs>) => PetNode;
  readonly search: (args: GQLensArgs<Types.QuerySearchArgs>) => { readonly refs: readonly EntityRef[] | undefined };
}

// Schema metadata consumed by @gqlens/core
const schemaMeta: SchemaMeta = {
  query: {
    type: "Query",
    identityKeys: ["id", "__typename"],
    fields: {
      "__typename": { name: "__typename", kind: "scalar" },
      "user": { name: "user", kind: "entity", typeName: "User", hasArgs: true },
      "viewer": { name: "viewer", kind: "entity", typeName: "User" },
      "post": { name: "post", kind: "entity", typeName: "Post", hasArgs: true },
      "posts": { name: "posts", kind: "list", typeName: "Post", hasArgs: true },
      "pet": { name: "pet", kind: "entity", typeName: "Pet", isAbstract: true, possibleTypes: ["Cat","Dog"], hasArgs: true },
      "search": { name: "search", kind: "list", typeName: "SearchResult", isAbstract: true, possibleTypes: ["User","Post"], hasArgs: true },
    },
  },
  planner: {
    roots: {
      "__typename": { returnsEntity: false },
      "user": { returnsEntity: true, graphQLType: "User", args: { "id": "ID!" } },
      "viewer": { returnsEntity: true, graphQLType: "User" },
      "post": { returnsEntity: true, graphQLType: "Post", args: { "id": "ID!" } },
      "posts": { returnsEntity: true, graphQLType: "Post", returnsList: true, args: { "first": "Int", "done": "Boolean" } },
      "pet": { returnsEntity: true, graphQLType: "Pet", isAbstract: true, possibleTypes: ["Cat","Dog"], args: { "id": "ID!" } },
      "search": { returnsEntity: true, graphQLType: "SearchResult", isAbstract: true, possibleTypes: ["User","Post"], returnsList: true, args: { "text": "String!" } },
    },
    types: {
      "Node": {
        "__typename": { returnsEntity: false, possibleTypes: ["User","Post"] },
        "id": { returnsEntity: false },
      },
      "User": {
        "__typename": { returnsEntity: false },
        "id": { returnsEntity: false },
        "name": { returnsEntity: false },
        "avatar": { returnsEntity: false },
        "online": { returnsEntity: false },
        "posts": { returnsEntity: true, graphQLType: "Post", returnsList: true },
      },
      "Post": {
        "__typename": { returnsEntity: false },
        "id": { returnsEntity: false },
        "title": { returnsEntity: false },
        "content": { returnsEntity: false },
        "tags": { returnsEntity: false, returnsList: true },
        "author": { returnsEntity: true, graphQLType: "User" },
        "comments": { returnsEntity: true, graphQLType: "Comment", returnsList: true },
      },
      "Comment": {
        "__typename": { returnsEntity: false },
        "id": { returnsEntity: false },
        "body": { returnsEntity: false },
        "author": { returnsEntity: true, graphQLType: "User" },
      },
      "Pet": {
        "__typename": { returnsEntity: false, possibleTypes: ["Cat","Dog"] },
        "id": { returnsEntity: false },
        "name": { returnsEntity: false },
      },
      "Cat": {
        "__typename": { returnsEntity: false },
        "id": { returnsEntity: false },
        "name": { returnsEntity: false },
        "meows": { returnsEntity: false },
      },
      "Dog": {
        "__typename": { returnsEntity: false },
        "id": { returnsEntity: false },
        "name": { returnsEntity: false },
        "barks": { returnsEntity: false },
      },
      "SearchResult": {
        "__typename": { returnsEntity: false, possibleTypes: ["User","Post"] },
      },
      "Query": {
        "__typename": { returnsEntity: false },
        "user": { returnsEntity: true, graphQLType: "User", args: { "id": "ID!" } },
        "viewer": { returnsEntity: true, graphQLType: "User" },
        "post": { returnsEntity: true, graphQLType: "Post", args: { "id": "ID!" } },
        "posts": { returnsEntity: true, graphQLType: "Post", returnsList: true, args: { "first": "Int", "done": "Boolean" } },
        "pet": { returnsEntity: true, graphQLType: "Pet", isAbstract: true, possibleTypes: ["Cat","Dog"], args: { "id": "ID!" } },
        "search": { returnsEntity: true, graphQLType: "SearchResult", isAbstract: true, possibleTypes: ["User","Post"], returnsList: true, args: { "text": "String!" } },
      },
      "Mutation": {
        "__typename": { returnsEntity: false },
        "renameUser": { returnsEntity: true, graphQLType: "User", args: { "id": "ID!", "name": "String!" } },
        "addComment": { returnsEntity: true, graphQLType: "Comment", args: { "postId": "ID!", "content": "String!" } },
      },
    },
  },
  entities: {
    "Node": {
      type: "Node",
      identityKeys: ["id", "__typename"],
      fields: {
        "__typename": { name: "__typename", kind: "scalar" },
        "id": { name: "id", kind: "scalar" },
      },
      isAbstract: true,
      possibleTypes: ["User","Post"],
      typeConditions: ["User","Post"],
    },
    "User": {
      type: "User",
      identityKeys: ["id", "__typename"],
      fields: {
        "__typename": { name: "__typename", kind: "scalar" },
        "id": { name: "id", kind: "scalar" },
        "name": { name: "name", kind: "scalar" },
        "avatar": { name: "avatar", kind: "scalar" },
        "online": { name: "online", kind: "scalar" },
        "posts": { name: "posts", kind: "list", typeName: "Post" },
      },
    },
    "Post": {
      type: "Post",
      identityKeys: ["id", "__typename"],
      fields: {
        "__typename": { name: "__typename", kind: "scalar" },
        "id": { name: "id", kind: "scalar" },
        "title": { name: "title", kind: "scalar" },
        "content": { name: "content", kind: "scalar" },
        "tags": { name: "tags", kind: "scalar" },
        "author": { name: "author", kind: "entity", typeName: "User" },
        "comments": { name: "comments", kind: "list", typeName: "Comment" },
      },
    },
    "Comment": {
      type: "Comment",
      identityKeys: ["id", "__typename"],
      fields: {
        "__typename": { name: "__typename", kind: "scalar" },
        "id": { name: "id", kind: "scalar" },
        "body": { name: "body", kind: "scalar" },
        "author": { name: "author", kind: "entity", typeName: "User" },
      },
    },
    "Pet": {
      type: "Pet",
      identityKeys: ["id", "__typename"],
      fields: {
        "__typename": { name: "__typename", kind: "scalar" },
        "id": { name: "id", kind: "scalar" },
        "name": { name: "name", kind: "scalar" },
      },
      isAbstract: true,
      possibleTypes: ["Cat","Dog"],
      typeConditions: ["Cat","Dog"],
    },
    "Cat": {
      type: "Cat",
      identityKeys: ["id", "__typename"],
      fields: {
        "__typename": { name: "__typename", kind: "scalar" },
        "id": { name: "id", kind: "scalar" },
        "name": { name: "name", kind: "scalar" },
        "meows": { name: "meows", kind: "scalar" },
      },
    },
    "Dog": {
      type: "Dog",
      identityKeys: ["id", "__typename"],
      fields: {
        "__typename": { name: "__typename", kind: "scalar" },
        "id": { name: "id", kind: "scalar" },
        "name": { name: "name", kind: "scalar" },
        "barks": { name: "barks", kind: "scalar" },
      },
    },
    "SearchResult": {
      type: "SearchResult",
      identityKeys: ["id", "__typename"],
      fields: {
        "__typename": { name: "__typename", kind: "scalar" },
      },
      isAbstract: true,
      possibleTypes: ["User","Post"],
      typeConditions: ["User","Post","Node"],
    },
  },
};

// useQuery runtime entrypoint
export function useQuery(config?: Partial<Omit<QuerySessionConfig, "metadata">>): QueryNode & { readonly loading: boolean; readonly error: Error | null } {
  const state = useGQLensSession({ ...config, metadata: schemaMeta.planner });
  const ctx: AccessorContext = {
    root: "Query",
    cache: state.cache,
    demand: (steps) => state.demand("Query", steps),
    read: state.read,
  };
  const accessor = createAccessorNode<QueryNode>(ctx, schemaMeta, schemaMeta.query) as QueryNode & { readonly loading: boolean; readonly error: Error | null };
  Object.defineProperties(accessor, {
    loading: { enumerable: true, get: () => state.loading },
    error: { enumerable: true, get: () => state.error },
  });
  return accessor;
}

// useLiveQuery runtime entrypoint
export function useLiveQuery(config?: Partial<Omit<QuerySessionConfig, "metadata">>): QueryNode & { readonly loading: boolean; readonly error: Error | null } {
  const state = useLiveGQLensSession({ ...config, metadata: schemaMeta.planner });
  const ctx: AccessorContext = {
    root: "Query",
    cache: state.cache,
    demand: (steps) => state.demand("Query", steps),
    read: state.read,
  };
  const accessor = createAccessorNode<QueryNode>(ctx, schemaMeta, schemaMeta.query) as QueryNode & { readonly loading: boolean; readonly error: Error | null };
  Object.defineProperties(accessor, {
    loading: { enumerable: true, get: () => state.loading },
    error: { enumerable: true, get: () => state.error },
  });
  return accessor;
}

// Static selector builders
export function defineSelection(callback: (q: QueryNode, v: (name: string) => VariablePlaceholder) => void): PreparedSelection {
  return defineGQLensSelection<QueryNode>(schemaMeta, schemaMeta.query, callback);
}

export function defineInvalidation(callback: (q: QueryNode) => unknown): InvalidationTarget {
  return defineGQLensInvalidation<QueryNode>(schemaMeta, schemaMeta.query, callback);
}

// Mutation operation descriptors
export const api: {
  readonly comment: {
    readonly add: MutationOperation<Types.MutationAddCommentArgs, Types.Comment>;
  };
  readonly user: {
    readonly rename: MutationOperation<Types.MutationRenameUserArgs, Types.User>;
  };
} = {
  comment: {
    add: {
      operationName: "addComment",
      query: "mutation addComment($postId: ID!, $content: String!) { addComment(postId: $postId, content: $content) { id __typename body } }",
      variables: (input: Types.MutationAddCommentArgs): Record<string, unknown> => ({
        postId: input.postId,
        content: input.content,
      }),
    },
  },
  user: {
    rename: {
      operationName: "renameUser",
      query: "mutation renameUser($id: ID!, $name: String!) { renameUser(id: $id, name: $name) { id __typename name avatar online } }",
      variables: (input: Types.MutationRenameUserArgs): Record<string, unknown> => ({
        id: input.id,
        name: input.name,
      }),
    },
  },
};

