// Auto-generated by @gqlens/codegen
import type { InvalidationTarget } from "@gqlens/core";

export type EntityInvalidationSpec = 
  | { readonly type: "User"; readonly id: string; readonly keys?: readonly ("id" | "name" | "avatar" | "online" | "id" | "__typename")[] }
  | { readonly type: "Post"; readonly id: string; readonly keys?: readonly ("id" | "title" | "content" | "id" | "__typename")[] }
  | { readonly type: "Comment"; readonly id: string; readonly keys?: readonly ("id" | "body" | "id" | "__typename")[] }
  | { readonly type: "Cat"; readonly id: string; readonly keys?: readonly ("id" | "name" | "meows" | "id" | "__typename")[] }
  | { readonly type: "Dog"; readonly id: string; readonly keys?: readonly ("id" | "name" | "barks" | "id" | "__typename")[] }
;

export type InvalidationSpec = EntityInvalidationSpec | InvalidationTarget;
