// Auto-generated by @gqlens/codegen
// Sections: typed nodes, schema metadata, runtime entrypoints, selectors, mutation API.
import { useGQLensSession, useLiveGQLensSession } from "@gqlens/react";
import {
  createAccessorNode,
  defineInvalidation as defineGQLensInvalidation,
  defineSelection as defineGQLensSelection,
  type AccessorContext,
  type SchemaMeta,
} from "@gqlens/core/codegen";
import type {
  InvalidationTarget,
  PreparedSelection,
  QuerySessionConfig,
  VariablePlaceholder,
} from "@gqlens/core";
import type * as Types from "./types";

type GQLensArgValue<T> =
  T extends readonly (infer Item)[]
    ? readonly GQLensArgValue<Item>[] | VariablePlaceholder
    : T extends object
      ? { readonly [Key in keyof T]: GQLensArgValue<T[Key]> } | VariablePlaceholder
      : T | VariablePlaceholder;
type GQLensArgs<T> = { readonly [Key in keyof T]: GQLensArgValue<T[Key]> };

// Typed accessor nodes
export interface ProfileNode {
  readonly __typename: string | undefined;
  readonly id: Types.Profile["id"] | undefined;
  readonly handle: Types.Profile["handle"] | undefined;
}

export interface QueryNode {
  readonly __typename: string | undefined;
  readonly profile: (args: GQLensArgs<Types.QueryProfileArgs>) => ProfileNode;
}

// Schema metadata consumed by @gqlens/core
const schemaMeta: SchemaMeta = {
  query: {
    type: "Query",
    identityKeys: ["id", "__typename"],
    fields: {
      "__typename": { name: "__typename", kind: "scalar" },
      "profile": { name: "profile", kind: "entity", typeName: "Profile", hasArgs: true },
    },
  },
  planner: {
    roots: {
      "__typename": { returnsEntity: false },
      "profile": { returnsEntity: true, graphQLType: "Profile", args: { "id": "ID!" } },
    },
    types: {
      "Profile": {
        "__typename": { returnsEntity: false },
        "id": { returnsEntity: false },
        "handle": { returnsEntity: false },
      },
      "Query": {
        "__typename": { returnsEntity: false },
        "profile": { returnsEntity: true, graphQLType: "Profile", args: { "id": "ID!" } },
      },
    },
  },
  entities: {
    "Profile": {
      type: "Profile",
      identityKeys: ["id", "__typename"],
      fields: {
        "__typename": { name: "__typename", kind: "scalar" },
        "id": { name: "id", kind: "scalar" },
        "handle": { name: "handle", kind: "scalar" },
      },
    },
  },
};

// useQuery runtime entrypoint
export function useQuery(config?: Partial<Omit<QuerySessionConfig, "metadata">>): QueryNode & { readonly loading: boolean; readonly error: Error | null } {
  const state = useGQLensSession({ ...config, metadata: schemaMeta.planner });
  const ctx: AccessorContext = {
    root: "Query",
    cache: state.cache,
    demand: (steps) => state.demand("Query", steps),
    read: state.read,
  };
  const accessor = createAccessorNode<QueryNode>(ctx, schemaMeta, schemaMeta.query) as QueryNode & { readonly loading: boolean; readonly error: Error | null };
  Object.defineProperties(accessor, {
    loading: { enumerable: true, get: () => state.loading },
    error: { enumerable: true, get: () => state.error },
  });
  return accessor;
}

// useLiveQuery runtime entrypoint
export function useLiveQuery(config?: Partial<Omit<QuerySessionConfig, "metadata">>): QueryNode & { readonly loading: boolean; readonly error: Error | null } {
  const state = useLiveGQLensSession({ ...config, metadata: schemaMeta.planner });
  const ctx: AccessorContext = {
    root: "Query",
    cache: state.cache,
    demand: (steps) => state.demand("Query", steps),
    read: state.read,
  };
  const accessor = createAccessorNode<QueryNode>(ctx, schemaMeta, schemaMeta.query) as QueryNode & { readonly loading: boolean; readonly error: Error | null };
  Object.defineProperties(accessor, {
    loading: { enumerable: true, get: () => state.loading },
    error: { enumerable: true, get: () => state.error },
  });
  return accessor;
}

// Static selector builders
export function defineSelection(callback: (q: QueryNode, v: (name: string) => VariablePlaceholder) => void): PreparedSelection {
  return defineGQLensSelection<QueryNode>(schemaMeta, schemaMeta.query, callback);
}

export function defineInvalidation(callback: (q: QueryNode) => unknown): InvalidationTarget {
  return defineGQLensInvalidation<QueryNode>(schemaMeta, schemaMeta.query, callback);
}

