// Auto-generated by @gqlens/codegen
// Sections: typed nodes, schema contract, runtime entrypoints, selectors, mutation API.
import { useGQLensSession, useLiveGQLensSession, type QueryConfig as GQLensQueryConfig } from "@gqlens/react";
import {
  bindSelection as bindGQLensSelection,
  createAccessorNode,
  defineInvalidation as defineGQLensInvalidation,
  defineSelection as defineGQLensSelection,
  type AccessorContext,
  type GQLensSchemaContract,
} from "@gqlens/core/codegen";
import type {
  GraphDataInvalidation,
  PreparedSelection,
  VariablePlaceholder,
} from "@gqlens/core";
import type * as Types from "./types";

type GQLensArgValue<T> =
  T extends readonly (infer Item)[]
    ? readonly GQLensArgValue<Item>[] | VariablePlaceholder
    : T extends object
      ? { readonly [Key in keyof T]: GQLensArgValue<T[Key]> } | VariablePlaceholder
      : T | VariablePlaceholder;
type GQLensArgs<T> = { readonly [Key in keyof T]: GQLensArgValue<T[Key]> };
type GQLensQueryOptions = Omit<GQLensQueryConfig, "schema">;

// Typed accessor nodes
export interface ProfileNode {
  readonly __typename: string | undefined;
  readonly id: Types.Profile["id"] | undefined;
  readonly handle: Types.Profile["handle"] | undefined;
}

export interface QueryNode {
  readonly __typename: string | undefined;
  readonly profile: (args: GQLensArgs<Types.QueryProfileArgs>) => ProfileNode;
}

// Schema contract consumed by @gqlens/core
export const gqlensSchema: GQLensSchemaContract = {
  query: {
    type: "Query",
    kind: "root",
    fields: {
      "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
      "profile": { name: "profile", result: { "kind": "object", "cardinality": "one", "typeName": "Profile", "objectKind": "entity" }, args: { "id": "ID!" } },
    },
  },
  objects: {
    "Profile": {
      type: "Profile",
      kind: "entity",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "id": { name: "id", result: { "kind": "scalar", "cardinality": "one" } },
        "handle": { name: "handle", result: { "kind": "scalar", "cardinality": "one" } },
      },
    },
  },
};

// useQuery runtime entrypoint
export function useQuery(config?: GQLensQueryOptions): QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void } {
  const state = useGQLensSession({ ...config, schema: gqlensSchema });
  const ctx: AccessorContext = {
    root: "Query",
    store: state.store,
    demand: (steps) => state.demand("Query", steps),
    read: state.read,
  };
  const accessor = createAccessorNode<QueryNode>(ctx, gqlensSchema, gqlensSchema.query) as QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void };
  Object.defineProperties(accessor, {
    loading: { enumerable: true, get: () => state.loading },
    error: { enumerable: true, get: () => state.error },
    refetch: { enumerable: true, value: () => state.session.refetch() },
  });
  return accessor;
}

// useLiveQuery runtime entrypoint
export function useLiveQuery(config?: GQLensQueryOptions): QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void } {
  const state = useLiveGQLensSession({ ...config, schema: gqlensSchema });
  const ctx: AccessorContext = {
    root: "Query",
    store: state.store,
    demand: (steps) => state.demand("Query", steps),
    read: state.read,
  };
  const accessor = createAccessorNode<QueryNode>(ctx, gqlensSchema, gqlensSchema.query) as QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void };
  Object.defineProperties(accessor, {
    loading: { enumerable: true, get: () => state.loading },
    error: { enumerable: true, get: () => state.error },
    refetch: { enumerable: true, value: () => state.session.refetch() },
  });
  return accessor;
}

// usePreparedQuery prepared runtime entrypoint
export function usePreparedQuery(selection: PreparedSelection, variables: Readonly<Record<string, unknown>>, config?: GQLensQueryOptions): QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void } {
  const state = useGQLensSession({ ...config, schema: gqlensSchema });
  for (const path of bindGQLensSelection(selection, variables)) {
    state.demand(path.root, path.steps);
  }
  const ctx: AccessorContext = {
    root: "Query",
    store: state.store,
    demand: (steps) => state.demand("Query", steps),
    read: state.read,
  };
  const accessor = createAccessorNode<QueryNode>(ctx, gqlensSchema, gqlensSchema.query) as QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void };
  Object.defineProperties(accessor, {
    loading: { enumerable: true, get: () => state.loading },
    error: { enumerable: true, get: () => state.error },
    refetch: { enumerable: true, value: () => state.session.refetch() },
  });
  return accessor;
}

// Static selector builders
export function defineSelection(callback: (q: QueryNode, v: (name: string) => VariablePlaceholder) => void): PreparedSelection {
  return defineGQLensSelection<QueryNode>(gqlensSchema, gqlensSchema.query, callback);
}

export function defineInvalidation(callback: (q: QueryNode) => unknown): GraphDataInvalidation {
  return defineGQLensInvalidation<QueryNode>(gqlensSchema, gqlensSchema.query, callback);
}

