// Auto-generated by @gqlens/codegen
import type { InvalidationTarget } from "@gqlens/core";

export type EntityInvalidationSpec = 
  | { readonly type: "Profile"; readonly id: string; readonly keys?: readonly ("id" | "handle" | "id" | "__typename")[] }
;

export type InvalidationSpec = EntityInvalidationSpec | InvalidationTarget;
