// Auto-generated by @gqlens/codegen
import type { NormalizerEntry } from "@gqlens/core/codegen";

export const normalizerEntries: NormalizerEntry[] = [
  { type: "Profile", fields: [
    { responseKey: "id", cacheKey: "id" },
    { responseKey: "handle", cacheKey: "handle" },
  ] },
];
