// Auto-generated by @gqlens/codegen
// Sections: typed nodes, schema metadata, runtime entrypoints, selectors, mutation API.
import { useGQLensSession, useLiveGQLensSession, type QueryConfig as GQLensQueryConfig } from "@gqlens/react";
import {
  bindSelection as bindGQLensSelection,
  createAccessorNode,
  defineInvalidation as defineGQLensInvalidation,
  defineSelection as defineGQLensSelection,
  type AccessorContext,
  type SchemaMeta,
} from "@gqlens/core/codegen";
import type {
  GraphDataInvalidation,
  MutationOperation,
  PreparedSelection,
  VariablePlaceholder,
} from "@gqlens/core";
import type * as Types from "./types";

type GQLensArgValue<T> =
  T extends readonly (infer Item)[]
    ? readonly GQLensArgValue<Item>[] | VariablePlaceholder
    : T extends object
      ? { readonly [Key in keyof T]: GQLensArgValue<T[Key]> } | VariablePlaceholder
      : T | VariablePlaceholder;
type GQLensArgs<T> = { readonly [Key in keyof T]: GQLensArgValue<T[Key]> };
type GQLensQueryOptions = Omit<GQLensQueryConfig, "metadata">;

// Typed accessor nodes
export interface UserNode {
  readonly __typename: string | undefined;
  readonly id: Types.User["id"] | undefined;
  readonly name: Types.User["name"] | undefined;
  readonly status: UserStatusNode;
}

export interface UserStatusNode {
  readonly __typename: string | undefined;
  readonly online: Types.UserStatus["online"] | undefined;
  readonly source: StatusSourceNode;
}

export interface StatusSourceNode {
  readonly __typename: string | undefined;
  readonly kind: Types.StatusSource["kind"] | undefined;
  readonly version: Types.StatusSource["version"] | undefined;
}

export interface PluginStatusNode {
  readonly __typename: string | undefined;
  readonly summary: PluginSummaryNode;
}

export interface PluginSummaryNode {
  readonly __typename: string | undefined;
  readonly total: Types.PluginSummary["total"] | undefined;
}

export interface QueryNode {
  readonly __typename: string | undefined;
  readonly user: (args: GQLensArgs<Types.QueryUserArgs>) => UserNode;
  readonly pluginStatus: PluginStatusNode;
}

// Schema metadata consumed by @gqlens/core
const schemaMeta: SchemaMeta = {
  query: {
    type: "Query",
    kind: "root",
    identityKeys: [],
    fields: {
      "__typename": { name: "__typename", kind: "scalar" },
      "user": { name: "user", kind: "entity", typeName: "User", targetObjectKind: "entity", hasArgs: true },
      "pluginStatus": { name: "pluginStatus", kind: "value", typeName: "PluginStatus", targetObjectKind: "value" },
    },
  },
  planner: {
    roots: {
      "__typename": { returnsEntity: false },
      "user": { returnsEntity: true, graphQLType: "User", targetObjectKind: "entity", args: { "id": "ID!" } },
      "pluginStatus": { returnsEntity: false, graphQLType: "PluginStatus", targetObjectKind: "value" },
    },
    types: {
      "User": {
        "__typename": { returnsEntity: false },
        "id": { returnsEntity: false },
        "name": { returnsEntity: false },
        "status": { returnsEntity: false, graphQLType: "UserStatus", targetObjectKind: "value" },
      },
      "UserStatus": {
        "__typename": { returnsEntity: false },
        "online": { returnsEntity: false },
        "source": { returnsEntity: false, graphQLType: "StatusSource", targetObjectKind: "value" },
      },
      "StatusSource": {
        "__typename": { returnsEntity: false },
        "kind": { returnsEntity: false },
        "version": { returnsEntity: false },
      },
      "PluginStatus": {
        "__typename": { returnsEntity: false },
        "summary": { returnsEntity: false, graphQLType: "PluginSummary", targetObjectKind: "value" },
      },
      "PluginSummary": {
        "__typename": { returnsEntity: false },
        "total": { returnsEntity: false },
      },
      "Query": {
        "__typename": { returnsEntity: false },
        "user": { returnsEntity: true, graphQLType: "User", targetObjectKind: "entity", args: { "id": "ID!" } },
        "pluginStatus": { returnsEntity: false, graphQLType: "PluginStatus", targetObjectKind: "value" },
      },
      "Mutation": {
        "__typename": { returnsEntity: false },
        "renameUser": { returnsEntity: true, graphQLType: "User", targetObjectKind: "entity", args: { "id": "ID!", "name": "String!" } },
      },
    },
  },
  entities: {
    "User": {
      type: "User",
      kind: "entity",
      identityKeys: ["id", "__typename"],
      fields: {
        "__typename": { name: "__typename", kind: "scalar" },
        "id": { name: "id", kind: "scalar" },
        "name": { name: "name", kind: "scalar" },
        "status": { name: "status", kind: "value", typeName: "UserStatus", targetObjectKind: "value" },
      },
    },
    "UserStatus": {
      type: "UserStatus",
      kind: "value",
      identityKeys: [],
      fields: {
        "__typename": { name: "__typename", kind: "scalar" },
        "online": { name: "online", kind: "scalar" },
        "source": { name: "source", kind: "value", typeName: "StatusSource", targetObjectKind: "value" },
      },
    },
    "StatusSource": {
      type: "StatusSource",
      kind: "value",
      identityKeys: [],
      fields: {
        "__typename": { name: "__typename", kind: "scalar" },
        "kind": { name: "kind", kind: "scalar" },
        "version": { name: "version", kind: "scalar" },
      },
    },
    "PluginStatus": {
      type: "PluginStatus",
      kind: "value",
      identityKeys: [],
      fields: {
        "__typename": { name: "__typename", kind: "scalar" },
        "summary": { name: "summary", kind: "value", typeName: "PluginSummary", targetObjectKind: "value" },
      },
    },
    "PluginSummary": {
      type: "PluginSummary",
      kind: "value",
      identityKeys: [],
      fields: {
        "__typename": { name: "__typename", kind: "scalar" },
        "total": { name: "total", kind: "scalar" },
      },
    },
  },
};

// useQuery runtime entrypoint
export function useQuery(config?: GQLensQueryOptions): QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void } {
  const state = useGQLensSession({ ...config, metadata: schemaMeta.planner });
  const ctx: AccessorContext = {
    root: "Query",
    store: state.store,
    demand: (steps) => state.demand("Query", steps),
    read: state.read,
  };
  const accessor = createAccessorNode<QueryNode>(ctx, schemaMeta, schemaMeta.query) as QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void };
  Object.defineProperties(accessor, {
    loading: { enumerable: true, get: () => state.loading },
    error: { enumerable: true, get: () => state.error },
    refetch: { enumerable: true, value: () => state.session.refetch() },
  });
  return accessor;
}

// useLiveQuery runtime entrypoint
export function useLiveQuery(config?: GQLensQueryOptions): QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void } {
  const state = useLiveGQLensSession({ ...config, metadata: schemaMeta.planner });
  const ctx: AccessorContext = {
    root: "Query",
    store: state.store,
    demand: (steps) => state.demand("Query", steps),
    read: state.read,
  };
  const accessor = createAccessorNode<QueryNode>(ctx, schemaMeta, schemaMeta.query) as QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void };
  Object.defineProperties(accessor, {
    loading: { enumerable: true, get: () => state.loading },
    error: { enumerable: true, get: () => state.error },
    refetch: { enumerable: true, value: () => state.session.refetch() },
  });
  return accessor;
}

// usePreparedQuery prepared runtime entrypoint
export function usePreparedQuery(selection: PreparedSelection, variables: Readonly<Record<string, unknown>>, config?: GQLensQueryOptions): QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void } {
  const state = useGQLensSession({ ...config, metadata: schemaMeta.planner });
  for (const path of bindGQLensSelection(selection, variables)) {
    state.demand(path.root, path.steps);
  }
  const ctx: AccessorContext = {
    root: "Query",
    store: state.store,
    demand: (steps) => state.demand("Query", steps),
    read: state.read,
  };
  const accessor = createAccessorNode<QueryNode>(ctx, schemaMeta, schemaMeta.query) as QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void };
  Object.defineProperties(accessor, {
    loading: { enumerable: true, get: () => state.loading },
    error: { enumerable: true, get: () => state.error },
    refetch: { enumerable: true, value: () => state.session.refetch() },
  });
  return accessor;
}

// Static selector builders
export function defineSelection(callback: (q: QueryNode, v: (name: string) => VariablePlaceholder) => void): PreparedSelection {
  return defineGQLensSelection<QueryNode>(schemaMeta, schemaMeta.query, callback);
}

export function defineInvalidation(callback: (q: QueryNode) => unknown): GraphDataInvalidation {
  return defineGQLensInvalidation<QueryNode>(schemaMeta, schemaMeta.query, callback);
}

// Mutation operation descriptors
export const api: {
  readonly user: {
    readonly rename: MutationOperation<Types.MutationRenameUserArgs, Pick<NonNullable<Types.Mutation["renameUser"]>, "id" | "__typename" | "name">>;
  };
} = {
  user: {
    rename: {
      operationName: "renameUser",
      query: "mutation renameUser($id: ID!, $name: String!) { renameUser(id: $id, name: $name) { id __typename name } }",
      metadata: schemaMeta.planner,
      variables: (input: Types.MutationRenameUserArgs): Record<string, unknown> => ({
        id: input.id,
        name: input.name,
      }),
    },
  },
};
