// Auto-generated by @gqlens/codegen
// Sections: typed nodes, schema contract, runtime entrypoints, selectors, mutation API.
import { useGQLensSession, useLiveGQLensSession, type QueryConfig as GQLensQueryConfig } from "@gqlens/react";
import {
  bindSelection as bindGQLensSelection,
  createAccessorNode,
  defineInvalidation as defineGQLensInvalidation,
  defineSelection as defineGQLensSelection,
  type AccessorContext,
  type GQLensSchemaContract,
} from "@gqlens/core/codegen";
import type {
  GraphDataInvalidation,
  MutationOperation,
  PreparedSelection,
  VariablePlaceholder,
} from "@gqlens/core";
import type * as Types from "./types";

type GQLensArgValue<T> =
  T extends readonly (infer Item)[]
    ? readonly GQLensArgValue<Item>[] | VariablePlaceholder
    : T extends object
      ? { readonly [Key in keyof T]: GQLensArgValue<T[Key]> } | VariablePlaceholder
      : T | VariablePlaceholder;
type GQLensArgs<T> = { readonly [Key in keyof T]: GQLensArgValue<T[Key]> };
type GQLensQueryOptions = Omit<GQLensQueryConfig, "schema">;

// Typed accessor nodes
export interface UserNode {
  readonly __typename: string | undefined;
  readonly id: Types.User["id"] | undefined;
  readonly name: Types.User["name"] | undefined;
  readonly status: UserStatusNode;
}

export interface UserStatusNode {
  readonly __typename: string | undefined;
  readonly online: Types.UserStatus["online"] | undefined;
  readonly source: StatusSourceNode;
}

export interface StatusSourceNode {
  readonly __typename: string | undefined;
  readonly kind: Types.StatusSource["kind"] | undefined;
  readonly version: Types.StatusSource["version"] | undefined;
}

export interface PluginStatusNode {
  readonly __typename: string | undefined;
  readonly summary: PluginSummaryNode;
}

export interface PluginSummaryNode {
  readonly __typename: string | undefined;
  readonly total: Types.PluginSummary["total"] | undefined;
}

export interface QueryNode {
  readonly __typename: string | undefined;
  readonly user: (args: GQLensArgs<Types.QueryUserArgs>) => UserNode;
  readonly pluginStatus: PluginStatusNode;
}

// Schema contract consumed by @gqlens/core
export const gqlensSchema: GQLensSchemaContract = {
  query: {
    type: "Query",
    kind: "root",
    fields: {
      "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
      "user": { name: "user", result: { "kind": "object", "cardinality": "one", "typeName": "User", "objectKind": "entity" }, args: { "id": "ID!" } },
      "pluginStatus": { name: "pluginStatus", result: { "kind": "object", "cardinality": "one", "typeName": "PluginStatus", "objectKind": "value" } },
    },
  },
  mutation: {
    type: "Mutation",
    kind: "root",
    fields: {
      "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
      "renameUser": { name: "renameUser", result: { "kind": "object", "cardinality": "one", "typeName": "User", "objectKind": "entity" }, args: { "id": "ID!", "name": "String!" } },
    },
  },
  objects: {
    "User": {
      type: "User",
      kind: "entity",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "id": { name: "id", result: { "kind": "scalar", "cardinality": "one" } },
        "name": { name: "name", result: { "kind": "scalar", "cardinality": "one" } },
        "status": { name: "status", result: { "kind": "object", "cardinality": "one", "typeName": "UserStatus", "objectKind": "value" } },
      },
    },
    "UserStatus": {
      type: "UserStatus",
      kind: "value",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "online": { name: "online", result: { "kind": "scalar", "cardinality": "one" } },
        "source": { name: "source", result: { "kind": "object", "cardinality": "one", "typeName": "StatusSource", "objectKind": "value" } },
      },
    },
    "StatusSource": {
      type: "StatusSource",
      kind: "value",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "kind": { name: "kind", result: { "kind": "scalar", "cardinality": "one" } },
        "version": { name: "version", result: { "kind": "scalar", "cardinality": "one" } },
      },
    },
    "PluginStatus": {
      type: "PluginStatus",
      kind: "value",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "summary": { name: "summary", result: { "kind": "object", "cardinality": "one", "typeName": "PluginSummary", "objectKind": "value" } },
      },
    },
    "PluginSummary": {
      type: "PluginSummary",
      kind: "value",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "total": { name: "total", result: { "kind": "scalar", "cardinality": "one" } },
      },
    },
  },
};

// useQuery runtime entrypoint
export function useQuery(config?: GQLensQueryOptions): QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void } {
  const state = useGQLensSession({ ...config, schema: gqlensSchema });
  const ctx: AccessorContext = {
    root: "Query",
    store: state.store,
    demand: (steps) => state.demand("Query", steps),
    read: state.read,
  };
  const accessor = createAccessorNode<QueryNode>(ctx, gqlensSchema, gqlensSchema.query) as QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void };
  Object.defineProperties(accessor, {
    loading: { enumerable: true, get: () => state.loading },
    error: { enumerable: true, get: () => state.error },
    refetch: { enumerable: true, value: () => state.session.refetch() },
  });
  return accessor;
}

// useLiveQuery runtime entrypoint
export function useLiveQuery(config?: GQLensQueryOptions): QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void } {
  const state = useLiveGQLensSession({ ...config, schema: gqlensSchema });
  const ctx: AccessorContext = {
    root: "Query",
    store: state.store,
    demand: (steps) => state.demand("Query", steps),
    read: state.read,
  };
  const accessor = createAccessorNode<QueryNode>(ctx, gqlensSchema, gqlensSchema.query) as QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void };
  Object.defineProperties(accessor, {
    loading: { enumerable: true, get: () => state.loading },
    error: { enumerable: true, get: () => state.error },
    refetch: { enumerable: true, value: () => state.session.refetch() },
  });
  return accessor;
}

// usePreparedQuery prepared runtime entrypoint
export function usePreparedQuery(selection: PreparedSelection, variables: Readonly<Record<string, unknown>>, config?: GQLensQueryOptions): QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void } {
  const state = useGQLensSession({ ...config, schema: gqlensSchema });
  for (const path of bindGQLensSelection(selection, variables)) {
    state.demand(path.root, path.steps);
  }
  const ctx: AccessorContext = {
    root: "Query",
    store: state.store,
    demand: (steps) => state.demand("Query", steps),
    read: state.read,
  };
  const accessor = createAccessorNode<QueryNode>(ctx, gqlensSchema, gqlensSchema.query) as QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void };
  Object.defineProperties(accessor, {
    loading: { enumerable: true, get: () => state.loading },
    error: { enumerable: true, get: () => state.error },
    refetch: { enumerable: true, value: () => state.session.refetch() },
  });
  return accessor;
}

// Static selector builders
export function defineSelection(callback: (q: QueryNode, v: (name: string) => VariablePlaceholder) => void): PreparedSelection {
  return defineGQLensSelection<QueryNode>(gqlensSchema, gqlensSchema.query, callback);
}

export function defineInvalidation(callback: (q: QueryNode) => unknown): GraphDataInvalidation {
  return defineGQLensInvalidation<QueryNode>(gqlensSchema, gqlensSchema.query, callback);
}

// Mutation operation descriptors
export const api: {
  readonly user: {
    readonly rename: MutationOperation<Types.MutationRenameUserArgs, Pick<NonNullable<Types.Mutation["renameUser"]>, "id" | "__typename" | "name">>;
  };
} = {
  user: {
    rename: {
      operationName: "renameUser",
      query: "mutation renameUser($id: ID!, $name: String!) { renameUser(id: $id, name: $name) { id __typename name } }",
      schema: gqlensSchema,
      variables: (input: Types.MutationRenameUserArgs): Record<string, unknown> => ({
        id: input.id,
        name: input.name,
      }),
    },
  },
};
