// Auto-generated by @gqlens/codegen
import type { NormalizerEntry } from "@gqlens/core/codegen";

export const normalizerEntries: NormalizerEntry[] = [
  { type: "User", fields: [
    { responseKey: "id", cacheKey: "id" },
    { responseKey: "name", cacheKey: "name" },
    { responseKey: "status", cacheKey: "status", nestedType: "UserStatus" },
  ] },
];
