import {
  type GraphQLField,
  type GraphQLInterfaceType,
  type GraphQLNamedType,
  type GraphQLObjectType,
  type GraphQLOutputType,
  type GraphQLSchema,
  type GraphQLUnionType,
  isEnumType,
  isInterfaceType,
  isListType,
  isNonNullType,
  isObjectType,
  isScalarType,
  isUnionType,
} from "graphql";
import type { AccessorAdapter } from "./adapters";
import { generatedArgsTypeName, generatedTypeName } from "./type-names";
import { unwrapOutput } from "./utils";

export function generateAccessor(schema: GraphQLSchema, adapter: AccessorAdapter): string {
  const queryType = schema.getQueryType();
  const mutationType = schema.getMutationType();

  const lines = [
    "// Auto-generated by @gqlens/codegen",
    `import { ${adapter.querySessionImport}, ${adapter.liveSessionImport} } from "${adapter.module}";`,
    'import { createAccessorNode, defineInvalidation as defineGQLensInvalidation, defineSelection as defineGQLensSelection } from "@gqlens/core/codegen";',
    'import type { AccessorContext, SchemaMeta } from "@gqlens/core/codegen";',
    'import type { EntityRef, MutationOperation, QuerySessionConfig } from "@gqlens/core";',
    'import type * as Types from "./types";',
    "",
    ...generateNodeInterfaces(schema),
    generateSchemaMeta(schema),
  ];

  if (queryType) {
    lines.push(generateHook(queryType, adapter.queryExport, adapter.querySessionHook));
    lines.push(generateHook(queryType, adapter.liveQueryExport, adapter.liveSessionHook));
    lines.push(generateSelectorBuilders(queryType));
  }
  if (mutationType) {
    lines.push(generateApi(mutationType));
  }

  return lines.join("\n");
}

function generateNodeInterfaces(schema: GraphQLSchema): string[] {
  const lines: string[] = [];
  for (const type of Object.values(schema.getTypeMap())) {
    if (
      !(isObjectType(type) || isInterfaceType(type) || isUnionType(type)) ||
      type.name.startsWith("__") ||
      type.name === "Mutation" ||
      type.name === "Subscription"
    ) {
      continue;
    }
    const nodeName = nodeTypeName(type.name);
    lines.push(`export interface ${nodeName} {`);
    lines.push(`  readonly __typename: string | undefined;`);
    if (isObjectType(type) || isInterfaceType(type)) {
      for (const field of Object.values(type.getFields())) {
        const signature = fieldSignature(type, field);
        lines.push(`  readonly ${signature};`);
      }
    }
    const typeConditions = typeConditionNames(schema, type);
    if (typeConditions.length > 0) {
      lines.push(`  readonly $on: {`);
      for (const typeName of typeConditions) {
        lines.push(`    readonly ${typeName}: ${nodeTypeName(typeName)};`);
      }
      lines.push(`  };`);
    }
    lines.push("}\n");
  }
  return lines;
}

function fieldSignature(
  owner: GraphQLObjectType | GraphQLInterfaceType,
  field: GraphQLField<unknown, unknown>,
): string {
  const returnType = nodeReturnType(owner, field);
  if (field.args.length === 0) {
    return `${field.name}: ${returnType}`;
  }
  const optional = field.args.every((arg) => !isNonNullType(arg.type)) ? "?" : "";
  return `${field.name}: (args${optional}: Types.${argsTypeName(owner, field)}) => ${returnType}`;
}

function nodeReturnType(
  owner: GraphQLObjectType | GraphQLInterfaceType,
  field: GraphQLField<unknown, unknown>,
): string {
  const unwrapped = unwrapOutput(field.type);
  if (isListTypeLike(field.type) && isCompositeType(unwrapped)) {
    if (isAbstractType(unwrapped)) {
      return "{ readonly refs: readonly EntityRef[] | undefined }";
    }
    return "{ readonly ids: readonly string[] | undefined }";
  }
  if (isCompositeType(unwrapped)) {
    return nodeTypeName(unwrapped.name);
  }
  return `Types.${generatedTypeName(owner.name)}[${JSON.stringify(field.name)}] | undefined`;
}

function generateHook(type: GraphQLObjectType, exportName: string, sessionHook: string): string {
  const nodeName = nodeTypeName(type.name);
  return [
    `export function ${exportName}(config?: Partial<Omit<QuerySessionConfig, "metadata">>): ${nodeName} & { readonly loading: boolean; readonly error: Error | null } {`,
    `  const state = ${sessionHook}({ ...config, metadata: schemaMeta.planner });`,
    `  const ctx: AccessorContext = {`,
    `    root: "${type.name}",`,
    `    cache: state.cache,`,
    `    demand: (steps) => state.demand("${type.name}", steps),`,
    `    read: state.read,`,
    `  };`,
    `  const accessor = createAccessorNode<${nodeName}>(ctx, schemaMeta, schemaMeta.query) as ${nodeName} & { readonly loading: boolean; readonly error: Error | null };`,
    `  Object.defineProperties(accessor, {`,
    `    loading: { enumerable: true, get: () => state.loading },`,
    `    error: { enumerable: true, get: () => state.error },`,
    `  });`,
    `  return accessor;`,
    `}`,
    "",
  ].join("\n");
}

function generateSelectorBuilders(type: GraphQLObjectType): string {
  const nodeName = nodeTypeName(type.name);
  return [
    `export function defineSelection(callback: (q: ${nodeName}, v: (name: string) => { readonly __gqlensVariable: string }) => void) {`,
    `  return defineGQLensSelection<${nodeName}>(schemaMeta, schemaMeta.query, callback);`,
    `}`,
    ``,
    `export function defineInvalidation(callback: (q: ${nodeName}) => unknown) {`,
    `  return defineGQLensInvalidation<${nodeName}>(schemaMeta, schemaMeta.query, callback);`,
    `}`,
    "",
  ].join("\n");
}

function generateSchemaMeta(schema: GraphQLSchema): string {
  const query = schema.getQueryType();
  const entities = Object.values(schema.getTypeMap()).filter(
    (type): type is GraphQLObjectType | GraphQLInterfaceType | GraphQLNamedType =>
      (isObjectType(type) || isInterfaceType(type) || isUnionType(type)) &&
      !type.name.startsWith("__") &&
      !["Query", "Mutation", "Subscription"].includes(type.name),
  );

  const lines = [
    "const schemaMeta: SchemaMeta = {",
    `  query: ${metaFor(query, "Query", schema)},`,
    `  planner: ${plannerMeta(schema)},`,
    "  entities: {",
  ];
  for (const entity of entities) {
    lines.push(`    ${JSON.stringify(entity.name)}: ${metaFor(entity, entity.name, schema)},`);
  }
  lines.push("  },", "};", "");
  return lines.join("\n");
}

function plannerMeta(schema: GraphQLSchema): string {
  const query = schema.getQueryType();
  const types = Object.values(schema.getTypeMap()).filter(
    (type): type is GraphQLObjectType | GraphQLInterfaceType | GraphQLNamedType =>
      (isObjectType(type) || isInterfaceType(type) || isUnionType(type)) &&
      !type.name.startsWith("__"),
  );
  const lines = ["{", `    roots: ${plannerFieldsFor(query, schema)},`, "    types: {"];
  for (const type of types) {
    lines.push(`      ${JSON.stringify(type.name)}: ${plannerFieldsFor(type, schema)},`);
  }
  lines.push("    },", "  }");
  return lines.join("\n");
}

function plannerFieldsFor(
  type: GraphQLObjectType | GraphQLInterfaceType | GraphQLNamedType | null | undefined,
  schema?: GraphQLSchema,
): string {
  if (!type) {
    return "{}";
  }
  const possibleTypes = schema ? possibleTypeNames(schema, type) : [];
  const typenameMeta =
    possibleTypes.length > 0
      ? `        "__typename": { returnsEntity: false, possibleTypes: ${JSON.stringify(possibleTypes)} },\n`
      : "";
  if (isUnionType(type)) {
    return `{\n${typenameMeta}      }`;
  }
  if (!isObjectType(type) && !isInterfaceType(type)) {
    return `{\n${typenameMeta}      }`;
  }

  const fields = [
    possibleTypes.length > 0 ? "" : `        "__typename": { returnsEntity: false },`,
    ...Object.values(type.getFields()).map((field) => {
      const unwrapped = unwrapOutput(field.type);
      const objectType = isCompositeType(unwrapped) ? unwrapped : undefined;
      const returnsObject = Boolean(objectType);
      const parts = [`returnsEntity: ${JSON.stringify(returnsObject)}`];
      if (objectType) {
        parts.push(`graphQLType: ${JSON.stringify(objectType.name)}`);
        const possible = schema ? possibleTypeNames(schema, objectType) : [];
        if (possible.length > 0) {
          parts.push("isAbstract: true");
          parts.push(`possibleTypes: ${JSON.stringify(possible)}`);
        }
      }
      if (isListTypeLike(field.type)) {
        parts.push("returnsList: true");
      }
      if (field.args.length > 0) {
        parts.push(
          `args: { ${field.args.map((arg) => `${JSON.stringify(arg.name)}: ${JSON.stringify(String(arg.type))}`).join(", ")} }`,
        );
      }
      return `        ${JSON.stringify(field.name)}: { ${parts.join(", ")} },`;
    }),
  ].filter((line) => line.length > 0);
  return `{\n${typenameMeta}${fields.join("\n")}\n      }`;
}

function metaFor(
  type: GraphQLObjectType | GraphQLInterfaceType | GraphQLNamedType | null | undefined,
  fallbackName: string,
  schema?: GraphQLSchema,
): string {
  if (!type) {
    return `{ type: ${JSON.stringify(fallbackName)}, identityKeys: ["id", "__typename"], fields: {} }`;
  }
  const possibleTypes = schema ? possibleTypeNames(schema, type) : [];
  const fields = [
    `      "__typename": { name: "__typename", kind: "scalar" },`,
    ...(isObjectType(type) || isInterfaceType(type) ? Object.values(type.getFields()) : []).map(
      (field) => {
        const unwrapped = unwrapOutput(field.type);
        const kind =
          isListTypeLike(field.type) && isCompositeType(unwrapped)
            ? "list"
            : isCompositeType(unwrapped)
              ? "entity"
              : "scalar";
        const typeName = isCompositeType(unwrapped)
          ? `, typeName: ${JSON.stringify(unwrapped.name)}`
          : "";
        const possible =
          schema && isCompositeType(unwrapped) ? possibleTypeNames(schema, unwrapped) : [];
        const abstract =
          possible.length > 0
            ? `, isAbstract: true, possibleTypes: ${JSON.stringify(possible)}`
            : "";
        const hasArgs = field.args.length > 0 ? ", hasArgs: true" : "";
        return `      ${JSON.stringify(field.name)}: { name: ${JSON.stringify(field.name)}, kind: ${JSON.stringify(kind)}${typeName}${abstract}${hasArgs} },`;
      },
    ),
  ];
  const abstractMeta =
    possibleTypes.length > 0
      ? `,\n    isAbstract: true,\n    possibleTypes: ${JSON.stringify(possibleTypes)},\n    typeConditions: ${JSON.stringify(schema ? typeConditionNames(schema, type) : [])}`
      : "";
  return `{\n    type: ${JSON.stringify(type.name)},\n    identityKeys: ["id", "__typename"],\n    fields: {\n${fields.join("\n")}\n    }${abstractMeta},\n  }`;
}

function generateApi(type: GraphQLObjectType): string {
  const groups = new Map<string, string[]>();
  for (const field of Object.values(type.getFields())) {
    const argsType =
      field.args.length > 0 ? `Types.${argsTypeName(type, field)}` : "Record<string, unknown>";
    const { group, action } = mutationApiName(field.name);
    const entries = groups.get(group) ?? [];
    entries.push(`    ${action}: ${mutationOperation(field, argsType)},`);
    groups.set(group, entries);
  }

  const lines = ["export const api = {"];
  for (const [group, entries] of [...groups.entries()].toSorted(([a], [b]) => a.localeCompare(b))) {
    lines.push(`  ${group}: {`, ...entries.toSorted(), "  },");
  }
  lines.push("};", "");
  return lines.join("\n");
}

function mutationOperation(field: GraphQLField<unknown, unknown>, argsType: string): string {
  return `{
      operationName: ${JSON.stringify(field.name)},
      query: ${JSON.stringify(mutationQuery(field))},
      variables: (input: ${argsType}) => (${mutationVariables(field)}),
    } satisfies MutationOperation<${argsType}, ${apiReturnType(field)}>`;
}

function mutationQuery(field: GraphQLField<unknown, unknown>): string {
  const declarations = field.args.map((arg) => `$${arg.name}: ${String(arg.type)}`).join(", ");
  const args = field.args.map((arg) => `${arg.name}: $${arg.name}`).join(", ");
  const selection = mutationSelection(field);
  const header = declarations
    ? `mutation ${field.name}(${declarations})`
    : `mutation ${field.name}`;
  const call = args ? `${field.name}(${args})` : field.name;
  return selection ? `${header} { ${call} { ${selection} } }` : `${header} { ${call} }`;
}

function mutationVariables(field: GraphQLField<unknown, unknown>): string {
  if (field.args.length === 0) {
    return "{}";
  }
  return `{ ${field.args.map((arg) => `${arg.name}: input.${arg.name}`).join(", ")} }`;
}

function mutationSelection(field: GraphQLField<unknown, unknown>): string {
  const unwrapped = unwrapOutput(field.type);
  if (!unwrapped || !isObjectType(unwrapped)) {
    return "";
  }
  const fields = Object.values(unwrapped.getFields())
    .filter((item) => isLeafType(item.type))
    .map((item) => item.name);
  const identity = unwrapped.getFields()["id"] ? ["id", "__typename"] : ["__typename"];
  return [...new Set([...identity, ...fields])].join(" ");
}

function apiReturnType(field: GraphQLField<unknown, unknown>): string {
  const unwrapped = unwrapOutput(field.type);
  if (unwrapped && isObjectType(unwrapped)) {
    return `Types.${generatedTypeName(unwrapped.name)}`;
  }
  return `Types.${generatedTypeName("Mutation")}[${JSON.stringify(field.name)}]`;
}

function isListTypeLike(type: unknown): boolean {
  if (isNonNullType(type)) {
    return isListTypeLike(type.ofType);
  }
  return isListType(type);
}

function isCompositeType(
  type: unknown,
): type is GraphQLObjectType | GraphQLInterfaceType | GraphQLUnionType {
  return isObjectType(type) || isInterfaceType(type) || isUnionType(type);
}

function isAbstractType(type: unknown): boolean {
  return isInterfaceType(type) || isUnionType(type);
}

function possibleTypeNames(schema: GraphQLSchema, type: GraphQLNamedType): string[] {
  if (isInterfaceType(type) || isUnionType(type)) {
    return schema.getPossibleTypes(type).map((item) => item.name);
  }
  return [];
}

function typeConditionNames(schema: GraphQLSchema, type: GraphQLNamedType): string[] {
  const possibleTypes = possibleTypeNames(schema, type);
  if (possibleTypes.length === 0) {
    return [];
  }

  const conditions = new Set(possibleTypes);
  for (const candidate of Object.values(schema.getTypeMap())) {
    if (!isInterfaceType(candidate) || candidate.name === type.name) {
      continue;
    }
    const candidateTypes = schema.getPossibleTypes(candidate).map((item) => item.name);
    if (candidateTypes.some((typeName) => possibleTypes.includes(typeName))) {
      conditions.add(candidate.name);
    }
  }
  return [...conditions];
}

function mutationApiName(fieldName: string): { group: string; action: string } {
  const match = /^(add|create|delete|remove|rename|set|toggle|update)([A-Z].*)$/.exec(fieldName);
  if (!match) {
    return { group: "mutation", action: fieldName };
  }

  return {
    group: lowerFirst(match[2]!),
    action: match[1]!,
  };
}

function lowerFirst(value: string): string {
  return `${value.slice(0, 1).toLowerCase()}${value.slice(1)}`;
}

function nodeTypeName(typeName: string): string {
  return `${generatedTypeName(typeName)}Node`;
}

function argsTypeName(
  owner: GraphQLObjectType | GraphQLInterfaceType,
  field: GraphQLField<unknown, unknown>,
): string {
  return generatedArgsTypeName(owner.name, field.name);
}

export function isLeafType(type: GraphQLOutputType): boolean {
  const unwrapped = unwrapOutput(type);
  return Boolean(unwrapped && (isScalarType(unwrapped) || isEnumType(unwrapped)));
}
