import CodeBlockWriter from "code-block-writer";
import {
  type GraphQLField,
  type GraphQLInterfaceType,
  type GraphQLNamedType,
  type GraphQLObjectType,
  type GraphQLOutputType,
  type GraphQLSchema,
  type GraphQLUnionType,
  isEnumType,
  isInterfaceType,
  isListType,
  isNonNullType,
  isObjectType,
  isScalarType,
  isUnionType,
} from "graphql";
import type { AccessorAdapter } from "./adapters";
import { generatedArgsTypeName, generatedTypeName } from "./type-names";
import { unwrapOutput } from "./utils";

export function generateAccessor(schema: GraphQLSchema, adapter: AccessorAdapter): string {
  const writer = createWriter();
  const queryType = schema.getQueryType();
  const mutationType = schema.getMutationType();

  writeHeader(writer, adapter);
  writeNodeInterfaces(writer, schema);
  writeSchemaMeta(writer, schema);

  if (queryType) {
    writeQueryHook(writer, queryType, adapter.queryExport, adapter.querySessionHook);
    writeQueryHook(writer, queryType, adapter.liveQueryExport, adapter.liveSessionHook);
    writeSelectorBuilders(writer, queryType);
  }

  if (mutationType) {
    writeMutationApi(writer, mutationType);
  }

  return writer.toString();
}

function createWriter(): CodeBlockWriter {
  return new CodeBlockWriter({ indentNumberOfSpaces: 2, useSingleQuote: false });
}

function writeHeader(writer: CodeBlockWriter, adapter: AccessorAdapter): void {
  writer.writeLine("// Auto-generated by @gqlens/codegen");
  writer.writeLine(
    "// Sections: typed nodes, schema metadata, runtime entrypoints, selectors, mutation API.",
  );
  writer.writeLine(
    `import { ${adapter.querySessionImport}, ${adapter.liveSessionImport} } from ${quote(adapter.module)};`,
  );
  writeNamedImport(writer, "@gqlens/core/codegen", [
    "createAccessorNode",
    "defineInvalidation as defineGQLensInvalidation",
    "defineSelection as defineGQLensSelection",
    "type AccessorContext",
    "type SchemaMeta",
  ]);
  writeNamedImport(
    writer,
    "@gqlens/core",
    [
      "EntityRef",
      "InvalidationTarget",
      "MutationOperation",
      "PreparedSelection",
      "QuerySessionConfig",
      "VariablePlaceholder",
    ],
    { typeOnly: true },
  );
  writer.writeLine('import type * as Types from "./types";');
  writer.blankLine();
  writer.writeLine("type GQLensArgValue<T> =");
  writer.indent(() => {
    writer.writeLine("T extends readonly (infer Item)[]");
    writer.indent(() => {
      writer.writeLine("? readonly GQLensArgValue<Item>[] | VariablePlaceholder");
      writer.writeLine(": T extends object");
      writer.indent(() => {
        writer.writeLine(
          "? { readonly [Key in keyof T]: GQLensArgValue<T[Key]> } | VariablePlaceholder",
        );
        writer.writeLine(": T | VariablePlaceholder;");
      });
    });
  });
  writer.writeLine("type GQLensArgs<T> = { readonly [Key in keyof T]: GQLensArgValue<T[Key]> };");
  writer.blankLine();
}

function writeNamedImport(
  writer: CodeBlockWriter,
  moduleName: string,
  names: readonly string[],
  options: { readonly typeOnly?: boolean } = {},
): void {
  writer.writeLine(`${options.typeOnly ? "import type" : "import"} {`);
  writer.indent(() => {
    for (const name of names) {
      writer.writeLine(`${name},`);
    }
  });
  writer.writeLine(`} from ${quote(moduleName)};`);
}

function writeNodeInterfaces(writer: CodeBlockWriter, schema: GraphQLSchema): void {
  writeSection(writer, "Typed accessor nodes");
  for (const type of accessorTypes(schema)) {
    writer.write(`export interface ${nodeTypeName(type.name)} `).block(() => {
      writer.writeLine("readonly __typename: string | undefined;");

      if (isObjectType(type) || isInterfaceType(type)) {
        for (const field of Object.values(type.getFields())) {
          writer.writeLine(`readonly ${fieldSignature(type, field)};`);
        }
      }

      const typeConditions = typeConditionNames(schema, type);
      if (typeConditions.length > 0) {
        writer.writeLine("readonly $on: {");
        writer.indent(() => {
          for (const typeName of typeConditions) {
            writer.writeLine(`readonly ${typeName}: ${nodeTypeName(typeName)};`);
          }
        });
        writer.writeLine("};");
      }
    });
    writer.blankLine();
  }
}

function fieldSignature(
  owner: GraphQLObjectType | GraphQLInterfaceType,
  field: GraphQLField<unknown, unknown>,
): string {
  const returnType = nodeReturnType(owner, field);
  if (field.args.length === 0) {
    return `${field.name}: ${returnType}`;
  }
  const optional = field.args.every((arg) => !isNonNullType(arg.type)) ? "?" : "";
  return `${field.name}: (args${optional}: GQLensArgs<Types.${argsTypeName(owner, field)}>) => ${returnType}`;
}

function nodeReturnType(
  owner: GraphQLObjectType | GraphQLInterfaceType,
  field: GraphQLField<unknown, unknown>,
): string {
  const unwrapped = unwrapOutput(field.type);
  if (isListTypeLike(field.type) && isCompositeType(unwrapped)) {
    if (isAbstractType(unwrapped)) {
      return "{ readonly refs: readonly EntityRef[] | undefined }";
    }
    return "{ readonly ids: readonly string[] | undefined }";
  }
  if (isCompositeType(unwrapped)) {
    return nodeTypeName(unwrapped.name);
  }
  return `Types.${generatedTypeName(owner.name)}[${quote(field.name)}] | undefined`;
}

function writeSchemaMeta(writer: CodeBlockWriter, schema: GraphQLSchema): void {
  writeSection(writer, "Schema metadata consumed by @gqlens/core");
  writer.writeLine("const schemaMeta: SchemaMeta = {");
  writer.indent(() => {
    writeEntityMetaProperty(writer, "query", schema.getQueryType(), "Query", schema);
    writePlannerMeta(writer, schema);
    writer.writeLine("entities: {");
    writer.indent(() => {
      for (const entity of generatedEntityTypes(schema)) {
        writeEntityMetaProperty(writer, quote(entity.name), entity, entity.name, schema);
      }
    });
    writer.writeLine("},");
  });
  writer.writeLine("};");
  writer.blankLine();
}

function writeQueryHook(
  writer: CodeBlockWriter,
  type: GraphQLObjectType,
  exportName: string,
  sessionHook: string,
): void {
  writeSection(writer, `${exportName} runtime entrypoint`);
  const nodeName = nodeTypeName(type.name);
  const resultType = `${nodeName} & { readonly loading: boolean; readonly error: Error | null }`;

  writer
    .write(
      `export function ${exportName}(config?: Partial<Omit<QuerySessionConfig, "metadata">>): ${resultType} `,
    )
    .block(() => {
      writer.writeLine(
        `const state = ${sessionHook}({ ...config, metadata: schemaMeta.planner });`,
      );
      writer.writeLine("const ctx: AccessorContext = {");
      writer.indent(() => {
        writer.writeLine(`root: ${quote(type.name)},`);
        writer.writeLine("cache: state.cache,");
        writer.writeLine(`demand: (steps) => state.demand(${quote(type.name)}, steps),`);
        writer.writeLine("read: state.read,");
      });
      writer.writeLine("};");
      writer.writeLine(
        `const accessor = createAccessorNode<${nodeName}>(ctx, schemaMeta, schemaMeta.query) as ${resultType};`,
      );
      writer.writeLine("Object.defineProperties(accessor, {");
      writer.indent(() => {
        writer.writeLine("loading: { enumerable: true, get: () => state.loading },");
        writer.writeLine("error: { enumerable: true, get: () => state.error },");
      });
      writer.writeLine("});");
      writer.writeLine("return accessor;");
    });
  writer.blankLine();
}

function writeSelectorBuilders(writer: CodeBlockWriter, type: GraphQLObjectType): void {
  writeSection(writer, "Static selector builders");
  const nodeName = nodeTypeName(type.name);

  writer
    .write(
      `export function defineSelection(callback: (q: ${nodeName}, v: (name: string) => VariablePlaceholder) => void): PreparedSelection `,
    )
    .block(() => {
      writer.writeLine(
        `return defineGQLensSelection<${nodeName}>(schemaMeta, schemaMeta.query, callback);`,
      );
    });
  writer.blankLine();

  writer
    .write(
      `export function defineInvalidation(callback: (q: ${nodeName}) => unknown): InvalidationTarget `,
    )
    .block(() => {
      writer.writeLine(
        `return defineGQLensInvalidation<${nodeName}>(schemaMeta, schemaMeta.query, callback);`,
      );
    });
  writer.blankLine();
}

function writeMutationApi(writer: CodeBlockWriter, type: GraphQLObjectType): void {
  writeSection(writer, "Mutation operation descriptors");
  const groups = mutationGroups(type);

  writer.writeLine("export const api: {");
  writer.indent(() => {
    for (const [group, fields] of groups) {
      writer.writeLine(`readonly ${group}: {`);
      writer.indent(() => {
        for (const field of fields) {
          const { action } = mutationApiName(field.name);
          writer.writeLine(`readonly ${action}: ${mutationOperationType(field)};`);
        }
      });
      writer.writeLine("};");
    }
  });
  writer.writeLine("} = {");
  writer.indent(() => {
    for (const [group, fields] of groups) {
      writer.writeLine(`${group}: {`);
      writer.indent(() => {
        for (const field of fields) {
          const { action } = mutationApiName(field.name);
          writeMutationOperation(writer, action, field);
        }
      });
      writer.writeLine("},");
    }
  });
  writer.writeLine("};");
  writer.blankLine();
}

function writeSection(writer: CodeBlockWriter, title: string): void {
  writer.writeLine(`// ${title}`);
}

function accessorTypes(
  schema: GraphQLSchema,
): Array<GraphQLObjectType | GraphQLInterfaceType | GraphQLUnionType> {
  return Object.values(schema.getTypeMap()).filter(
    (type): type is GraphQLObjectType | GraphQLInterfaceType | GraphQLUnionType =>
      (isObjectType(type) || isInterfaceType(type) || isUnionType(type)) &&
      !type.name.startsWith("__") &&
      type.name !== "Mutation" &&
      type.name !== "Subscription",
  );
}

function generatedEntityTypes(
  schema: GraphQLSchema,
): Array<GraphQLObjectType | GraphQLInterfaceType | GraphQLUnionType> {
  return Object.values(schema.getTypeMap()).filter(
    (type): type is GraphQLObjectType | GraphQLInterfaceType | GraphQLUnionType =>
      (isObjectType(type) || isInterfaceType(type) || isUnionType(type)) &&
      !type.name.startsWith("__") &&
      !["Query", "Mutation", "Subscription"].includes(type.name),
  );
}

function writePlannerMeta(writer: CodeBlockWriter, schema: GraphQLSchema): void {
  const query = schema.getQueryType();
  const types = Object.values(schema.getTypeMap()).filter(
    (type): type is GraphQLObjectType | GraphQLInterfaceType | GraphQLUnionType =>
      (isObjectType(type) || isInterfaceType(type) || isUnionType(type)) &&
      !type.name.startsWith("__"),
  );

  writer.writeLine("planner: {");
  writer.indent(() => {
    writePlannerFieldMapProperty(writer, "roots", query, schema);
    writer.writeLine("types: {");
    writer.indent(() => {
      for (const type of types) {
        writePlannerFieldMapProperty(writer, quote(type.name), type, schema);
      }
    });
    writer.writeLine("},");
  });
  writer.writeLine("},");
}

function writePlannerFieldMapProperty(
  writer: CodeBlockWriter,
  propertyName: string,
  type: GraphQLObjectType | GraphQLInterfaceType | GraphQLUnionType | null | undefined,
  schema: GraphQLSchema,
): void {
  writer.writeLine(`${propertyName}: {`);
  writer.indent(() => {
    for (const field of plannerFieldEntriesFor(type, schema)) {
      writer.writeLine(`${field},`);
    }
  });
  writer.writeLine("},");
}

function plannerFieldEntriesFor(
  type: GraphQLObjectType | GraphQLInterfaceType | GraphQLUnionType | null | undefined,
  schema: GraphQLSchema,
): string[] {
  if (!type) {
    return [];
  }
  const possibleTypes = possibleTypeNames(schema, type);
  if (isUnionType(type)) {
    return [typenamePlannerMeta(possibleTypes)];
  }
  if (!isObjectType(type) && !isInterfaceType(type)) {
    return [typenamePlannerMeta(possibleTypes)];
  }

  return [
    ...(possibleTypes.length > 0
      ? [typenamePlannerMeta(possibleTypes)]
      : [fieldMeta("__typename", ["returnsEntity: false"])]),
    ...Object.values(type.getFields()).map((field) => plannerFieldEntry(field, schema)),
  ];
}

function plannerFieldEntry(field: GraphQLField<unknown, unknown>, schema: GraphQLSchema): string {
  const unwrapped = unwrapOutput(field.type);
  const objectType = isCompositeType(unwrapped) ? unwrapped : undefined;
  const parts = [`returnsEntity: ${JSON.stringify(Boolean(objectType))}`];
  if (objectType) {
    parts.push(`graphQLType: ${quote(objectType.name)}`);
    const possible = possibleTypeNames(schema, objectType);
    if (possible.length > 0) {
      parts.push("isAbstract: true");
      parts.push(`possibleTypes: ${json(possible)}`);
    }
  }
  if (isListTypeLike(field.type)) {
    parts.push("returnsList: true");
  }
  if (field.args.length > 0) {
    parts.push(
      `args: ${objectLiteral(field.args.map((arg) => objectEntry(arg.name, quote(String(arg.type)))))}`,
    );
  }
  return fieldMeta(field.name, parts);
}

function typenamePlannerMeta(possibleTypes: readonly string[]): string {
  return fieldMeta("__typename", [
    "returnsEntity: false",
    ...(possibleTypes.length > 0 ? [`possibleTypes: ${json(possibleTypes)}`] : []),
  ]);
}

function writeEntityMetaProperty(
  writer: CodeBlockWriter,
  propertyName: string,
  type: GraphQLObjectType | GraphQLInterfaceType | GraphQLUnionType | null | undefined,
  fallbackName: string,
  schema: GraphQLSchema,
): void {
  writer.writeLine(`${propertyName}: {`);
  writer.indent(() => {
    writer.writeLine(`type: ${quote(type?.name ?? fallbackName)},`);
    writer.writeLine('identityKeys: ["id", "__typename"],');
    writer.writeLine("fields: {");
    writer.indent(() => {
      for (const field of entityFieldEntriesFor(type, schema)) {
        writer.writeLine(`${field},`);
      }
    });
    writer.writeLine("},");

    if (type) {
      const possibleTypes = possibleTypeNames(schema, type);
      if (possibleTypes.length > 0) {
        writer.writeLine("isAbstract: true,");
        writer.writeLine(`possibleTypes: ${json(possibleTypes)},`);
        writer.writeLine(`typeConditions: ${json(typeConditionNames(schema, type))},`);
      }
    }
  });
  writer.writeLine("},");
}

function entityFieldEntriesFor(
  type: GraphQLObjectType | GraphQLInterfaceType | GraphQLUnionType | null | undefined,
  schema: GraphQLSchema,
): string[] {
  if (!type) {
    return [];
  }
  return [
    fieldMeta("__typename", [`name: ${quote("__typename")}`, `kind: ${quote("scalar")}`]),
    ...(isObjectType(type) || isInterfaceType(type)
      ? Object.values(type.getFields()).map((field) => entityFieldEntry(field, schema))
      : []),
  ];
}

function entityFieldEntry(field: GraphQLField<unknown, unknown>, schema: GraphQLSchema): string {
  const unwrapped = unwrapOutput(field.type);
  const compositeType = isCompositeType(unwrapped) ? unwrapped : undefined;
  const kind =
    isListTypeLike(field.type) && compositeType ? "list" : compositeType ? "entity" : "scalar";
  const possible = compositeType ? possibleTypeNames(schema, compositeType) : [];
  const parts = [
    `name: ${quote(field.name)}`,
    `kind: ${quote(kind)}`,
    ...(compositeType ? [`typeName: ${quote(compositeType.name)}`] : []),
    ...(possible.length > 0 ? ["isAbstract: true", `possibleTypes: ${json(possible)}`] : []),
    ...(field.args.length > 0 ? ["hasArgs: true"] : []),
  ];
  return fieldMeta(field.name, parts);
}

function mutationGroups(
  type: GraphQLObjectType,
): Array<[string, GraphQLField<unknown, unknown>[]]> {
  const groups = new Map<string, GraphQLField<unknown, unknown>[]>();
  for (const field of Object.values(type.getFields())) {
    const { group } = mutationApiName(field.name);
    const fields = groups.get(group) ?? [];
    fields.push(field);
    groups.set(group, fields);
  }
  return [...groups.entries()]
    .toSorted(([a], [b]) => a.localeCompare(b))
    .map(([group, fields]) => [
      group,
      fields.toSorted((a, b) =>
        mutationApiName(a.name).action.localeCompare(mutationApiName(b.name).action),
      ),
    ]);
}

function writeMutationOperation(
  writer: CodeBlockWriter,
  action: string,
  field: GraphQLField<unknown, unknown>,
): void {
  const argsType = mutationArgsType(field);
  writer.writeLine(`${action}: {`);
  writer.indent(() => {
    writer.writeLine(`operationName: ${quote(field.name)},`);
    writer.writeLine(`query: ${quote(mutationQuery(field))},`);
    writeMutationVariables(writer, field, argsType);
  });
  writer.writeLine("},");
}

function mutationOperationType(field: GraphQLField<unknown, unknown>): string {
  return `MutationOperation<${mutationArgsType(field)}, ${apiReturnType(field)}>`;
}

function writeMutationVariables(
  writer: CodeBlockWriter,
  field: GraphQLField<unknown, unknown>,
  argsType: string,
): void {
  if (field.args.length === 0) {
    writer.writeLine(`variables: (input: ${argsType}): Record<string, unknown> => {`);
    writer.indent(() => {
      writer.writeLine("void input;");
      writer.writeLine("return {};");
    });
    writer.writeLine("},");
    return;
  }

  writer.writeLine(`variables: (input: ${argsType}): Record<string, unknown> => ({`);
  writer.indent(() => {
    for (const arg of field.args) {
      writer.writeLine(`${arg.name}: input.${arg.name},`);
    }
  });
  writer.writeLine("}),");
}

function mutationArgsType(field: GraphQLField<unknown, unknown>): string {
  const argsType =
    field.args.length > 0
      ? `Types.${generatedArgsTypeName("Mutation", field.name)}`
      : "Record<string, unknown>";
  return argsType;
}

function mutationQuery(field: GraphQLField<unknown, unknown>): string {
  const declarations = field.args.map((arg) => `$${arg.name}: ${String(arg.type)}`).join(", ");
  const args = field.args.map((arg) => `${arg.name}: $${arg.name}`).join(", ");
  const selection = mutationSelection(field);
  const header = declarations
    ? `mutation ${field.name}(${declarations})`
    : `mutation ${field.name}`;
  const call = args ? `${field.name}(${args})` : field.name;
  return selection ? `${header} { ${call} { ${selection} } }` : `${header} { ${call} }`;
}

function mutationSelection(field: GraphQLField<unknown, unknown>): string {
  const unwrapped = unwrapOutput(field.type);
  if (!unwrapped || !isObjectType(unwrapped)) {
    return "";
  }
  const fields = Object.values(unwrapped.getFields())
    .filter((item) => isLeafType(item.type))
    .map((item) => item.name);
  const identity = unwrapped.getFields()["id"] ? ["id", "__typename"] : ["__typename"];
  return [...new Set([...identity, ...fields])].join(" ");
}

function apiReturnType(field: GraphQLField<unknown, unknown>): string {
  const unwrapped = unwrapOutput(field.type);
  if (unwrapped && isObjectType(unwrapped)) {
    return `Types.${generatedTypeName(unwrapped.name)}`;
  }
  return `Types.${generatedTypeName("Mutation")}[${quote(field.name)}]`;
}

function objectLiteral(entries: readonly string[]): string {
  if (entries.length === 0) {
    return "{}";
  }
  return `{ ${entries.join(", ")} }`;
}

function objectEntry(key: string, value: string): string {
  return `${quote(key)}: ${value}`;
}

function fieldMeta(key: string, parts: readonly string[]): string {
  return `${quote(key)}: { ${parts.join(", ")} }`;
}

function quote(value: string): string {
  return JSON.stringify(value);
}

function json(value: unknown): string {
  return JSON.stringify(value);
}

function isListTypeLike(type: unknown): boolean {
  if (isNonNullType(type)) {
    return isListTypeLike(type.ofType);
  }
  return isListType(type);
}

function isCompositeType(
  type: unknown,
): type is GraphQLObjectType | GraphQLInterfaceType | GraphQLUnionType {
  return isObjectType(type) || isInterfaceType(type) || isUnionType(type);
}

function isAbstractType(type: unknown): boolean {
  return isInterfaceType(type) || isUnionType(type);
}

function possibleTypeNames(schema: GraphQLSchema, type: GraphQLNamedType): string[] {
  if (isInterfaceType(type) || isUnionType(type)) {
    return schema.getPossibleTypes(type).map((item) => item.name);
  }
  return [];
}

function typeConditionNames(schema: GraphQLSchema, type: GraphQLNamedType): string[] {
  const possibleTypes = possibleTypeNames(schema, type);
  if (possibleTypes.length === 0) {
    return [];
  }

  const conditions = new Set(possibleTypes);
  for (const candidate of Object.values(schema.getTypeMap())) {
    if (!isInterfaceType(candidate) || candidate.name === type.name) {
      continue;
    }
    const candidateTypes = schema.getPossibleTypes(candidate).map((item) => item.name);
    if (candidateTypes.some((typeName) => possibleTypes.includes(typeName))) {
      conditions.add(candidate.name);
    }
  }
  return [...conditions];
}

function mutationApiName(fieldName: string): { group: string; action: string } {
  const match = /^(add|create|delete|remove|rename|set|toggle|update)([A-Z].*)$/.exec(fieldName);
  if (!match) {
    return { group: "mutation", action: fieldName };
  }

  return {
    group: lowerFirst(match[2]!),
    action: match[1]!,
  };
}

function lowerFirst(value: string): string {
  return `${value.slice(0, 1).toLowerCase()}${value.slice(1)}`;
}

function nodeTypeName(typeName: string): string {
  return `${generatedTypeName(typeName)}Node`;
}

function argsTypeName(
  owner: GraphQLObjectType | GraphQLInterfaceType | undefined,
  field: GraphQLField<unknown, unknown>,
): string {
  return generatedArgsTypeName(owner?.name ?? "Mutation", field.name);
}

export function isLeafType(type: GraphQLOutputType): boolean {
  const unwrapped = unwrapOutput(type);
  return Boolean(unwrapped && (isScalarType(unwrapped) || isEnumType(unwrapped)));
}
