import type { GraphQLSchema } from "graphql";

export function generateInvalidation(schema: GraphQLSchema): string {
  void schema;
  const lines = [
    "// Auto-generated by @gqlens/codegen",
    'import type { GraphDataInvalidation } from "@gqlens/core";',
    "",
    "export type Invalidation = GraphDataInvalidation;\n",
  ];

  return lines.join("\n");
}
