import {
  type GraphQLObjectType,
  type GraphQLSchema,
  isListType,
  isNonNullType,
  isObjectType,
} from "graphql";
import { getEntityTypes, isScalarOrEnum } from "./utils";

export function generateNormalizer(schema: GraphQLSchema): string {
  const lines = [
    "// Auto-generated by @gqlens/codegen",
    'import type { NormalizerEntry } from "@gqlens/core/codegen";',
    "",
    "export const normalizerEntries: NormalizerEntry[] = [",
  ];

  for (const type of getEntityTypes(schema)) {
    lines.push(`  { type: "${type.name}", fields: [`);
    for (const field of Object.values(type.getFields())) {
      const unwrapped = unwrapOutput(field.type);
      const nested =
        unwrapped && isObjectType(unwrapped) && !isRootType(unwrapped.name)
          ? `, nestedType: "${unwrapped.name}"`
          : "";
      const asList = isListField(field.type) ? ", isList: true" : "";
      lines.push(
        `    { responseKey: "${field.name}", cacheKey: "${field.name}"${nested}${asList} },`,
      );
    }
    lines.push("  ] },");
  }

  lines.push("];\n");
  return lines.join("\n");
}

export function generateInvalidation(schema: GraphQLSchema): string {
  const lines = [
    "// Auto-generated by @gqlens/codegen",
    'import type { InvalidationTarget } from "@gqlens/core";',
    "",
    "export type EntityInvalidationSpec = ",
  ];

  for (const type of getEntityTypes(schema)) {
    const scalarFields = Object.values(type.getFields())
      .filter((f) => isScalarOrEnum(f.type))
      .map((f) => `"${f.name}"`);
    const keys = [...scalarFields, '"id"', '"__typename"'].join(" | ");
    lines.push(
      `  | { readonly type: "${type.name}"; readonly id: string; readonly keys?: readonly (${keys})[] }`,
    );
  }

  lines.push(";");
  lines.push("");
  lines.push("export type InvalidationSpec = EntityInvalidationSpec | InvalidationTarget;\n");
  return lines.join("\n");
}

function unwrapOutput(type: unknown): GraphQLObjectType | null {
  let t = type;
  if (isNonNullType(t)) {
    t = t.ofType;
  }
  if (isListType(t)) {
    t = t.ofType;
  }
  if (isNonNullType(t)) {
    t = t.ofType;
  }
  return isObjectType(t) ? t : null;
}

function isListField(type: unknown): boolean {
  return isListType(type) || (isNonNullType(type) && isListType(type.ofType));
}

function isRootType(name: string): boolean {
  return name === "Query" || name === "Mutation" || name === "Subscription";
}
