import { parse, buildASTSchema } from "graphql";
import { outputTsType } from "./utils";

export async function generateTypes(schemaSDL: string): Promise<string> {
  try {
    const { codegen } = await import("@graphql-codegen/core");
    const tsPlugin = await import("@graphql-codegen/typescript");
    const result = await codegen({
      filename: "types.ts",
      plugins: [{ typescript: { enumsAsTypes: true } }],
      schema: parse(schemaSDL),
      documents: [],
      pluginMap: { typescript: tsPlugin as never },
      config: {},
    });
    return (result as string) || fallback(schemaSDL);
  } catch {
    return fallback(schemaSDL);
  }
}

function fallback(schemaSDL: string): string {
  const schema = buildASTSchema(parse(schemaSDL));
  const lines = ["// Auto-generated by @gqlens/codegen", ""];
  for (const type of Object.values(schema.getTypeMap())) {
    if (type.name.startsWith("__")) {
      continue;
    }
    if ("getValues" in type) {
      lines.push(`export enum ${type.name} {`);
      for (const v of type.getValues()) {
        lines.push(`  ${v.name} = "${v.name}",`);
      }
      lines.push("}\n");
    } else if ("getFields" in type && !["Query", "Mutation", "Subscription"].includes(type.name)) {
      lines.push(`export interface ${type.name} {`);
      for (const f of Object.values(type.getFields())) {
        lines.push(`  ${f.name}${isRequired(f.type) ? "" : "?"}: ${outputTsType(f.type)};`);
      }
      lines.push("}\n");
    }
  }
  return lines.join("\n");
}

function isRequired(type: unknown): boolean {
  return (
    typeof type === "object" && type !== null && "toString" in type && String(type).includes("!")
  );
}
