import type CodeBlockWriter from "code-block-writer";
import { type GraphQLSchema, isInterfaceType, isObjectType } from "graphql";
import type { AccessorAdapter } from "../adapters";
import { unwrapOutput } from "../utils";
import { accessorTypes, isAbstractType, isListTypeLike, quote, writeNamedImport } from "./shared";

export function writeHeader(
  writer: CodeBlockWriter,
  schema: GraphQLSchema,
  adapter: AccessorAdapter,
): void {
  writer.writeLine("// Auto-generated by @gqlens/codegen");
  writer.writeLine(
    "// Sections: typed nodes, schema contract, runtime entrypoints, selectors, mutation API.",
  );
  writer.writeLine(
    `import { ${[adapter.querySessionImport, adapter.liveSessionImport, adapter.queryConfigImport].filter(Boolean).join(", ")} } from ${quote(adapter.module)};`,
  );
  writeNamedImport(writer, "@gqlens/core/codegen", [
    "bindSelection as bindGQLensSelection",
    "createAccessorNode",
    "defineInvalidation as defineGQLensInvalidation",
    "defineSelection as defineGQLensSelection",
    "type AccessorContext",
    "type GQLensSchemaContract",
  ]);
  const coreTypes = [
    "GraphDataInvalidation",
    ...(usesEntityRef(schema) ? ["EntityRef"] : []),
    ...(schema.getMutationType() ? ["MutationOperation"] : []),
    "PreparedSelection",
    ...(adapter.queryConfigType ? [] : ["QuerySessionConfig"]),
    "VariablePlaceholder",
  ];
  writeNamedImport(writer, "@gqlens/core", coreTypes, { typeOnly: true });
  writer.writeLine('import type * as Types from "./types";');
  writer.blankLine();
  writer.writeLine("type GQLensArgValue<T> =");
  writer.indent(() => {
    writer.writeLine("T extends readonly (infer Item)[]");
    writer.indent(() => {
      writer.writeLine("? readonly GQLensArgValue<Item>[] | VariablePlaceholder");
      writer.writeLine(": T extends object");
      writer.indent(() => {
        writer.writeLine(
          "? { readonly [Key in keyof T]: GQLensArgValue<T[Key]> } | VariablePlaceholder",
        );
        writer.writeLine(": T | VariablePlaceholder;");
      });
    });
  });
  writer.writeLine("type GQLensArgs<T> = { readonly [Key in keyof T]: GQLensArgValue<T[Key]> };");
  writer.writeLine(`type GQLensQueryOptions = Omit<${queryConfigType(adapter)}, "schema">;`);
  writer.blankLine();
}

function usesEntityRef(schema: GraphQLSchema): boolean {
  return accessorTypes(schema).some((type) => {
    if (!isObjectType(type) && !isInterfaceType(type)) {
      return false;
    }
    return Object.values(type.getFields()).some((field) => {
      const unwrapped = unwrapOutput(field.type);
      return isListTypeLike(field.type) && isAbstractType(unwrapped);
    });
  });
}

function queryConfigType(adapter: AccessorAdapter): string {
  return adapter.queryConfigType ?? "QuerySessionConfig";
}
