// Auto-generated by @gqlens/codegen
// Sections: typed nodes, schema contract, runtime entrypoints, selectors, mutation API.
import { useGQLensSession, useLiveGQLensSession, type QueryConfig as GQLensQueryConfig } from "@gqlens/react";
import {
  bindSelection as bindGQLensSelection,
  createAccessorNode,
  defineInvalidation as defineGQLensInvalidation,
  defineSelection as defineGQLensSelection,
  type AccessorContext,
  type GQLensSchemaContract,
} from "@gqlens/core/codegen";
import type {
  GraphDataInvalidation,
  MutationOperation,
  PreparedSelection,
  VariablePlaceholder,
} from "@gqlens/core";
import type * as Types from "./types";

type GQLensArgValue<T> =
  T extends readonly (infer Item)[]
    ? readonly GQLensArgValue<Item>[] | VariablePlaceholder
    : T extends object
      ? { readonly [Key in keyof T]: GQLensArgValue<T[Key]> } | VariablePlaceholder
      : T | VariablePlaceholder;
type GQLensArgs<T> = { readonly [Key in keyof T]: GQLensArgValue<T[Key]> };
type GQLensQueryOptions = Omit<GQLensQueryConfig, "schema">;

// Typed accessor nodes
export interface ReportNode {
  readonly __typename: string | undefined;
  readonly id: Types.Report["id"] | undefined;
  readonly title: Types.Report["title"] | undefined;
  readonly createdAt: Types.Report["createdAt"] | undefined;
}

export interface AuditEventNode {
  readonly __typename: string | undefined;
  readonly id: Types.AuditEvent["id"] | undefined;
  readonly message: Types.AuditEvent["message"] | undefined;
}

export interface QueryNode {
  readonly __typename: string | undefined;
  readonly reports: (args?: GQLensArgs<Types.QueryReportsArgs>) => { readonly ids: readonly string[] | undefined };
  readonly latestReport: ReportNode;
}

// Schema contract consumed by @gqlens/core
export const gqlensSchema: GQLensSchemaContract = {
  query: {
    type: "Query",
    kind: "root",
    fields: {
      "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
      "reports": { name: "reports", result: { "kind": "object", "cardinality": "list", "typeName": "Report", "objectKind": "entity" }, args: { "filter": "SearchFilter", "ids": "[ID!]", "limit": "Int" } },
      "latestReport": { name: "latestReport", result: { "kind": "object", "cardinality": "one", "typeName": "Report", "objectKind": "entity" } },
    },
  },
  mutation: {
    type: "Mutation",
    kind: "root",
    fields: {
      "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
      "ping": { name: "ping", result: { "kind": "scalar", "cardinality": "one" } },
      "rebuildIndex": { name: "rebuildIndex", result: { "kind": "scalar", "cardinality": "one" } },
      "renameReport": { name: "renameReport", result: { "kind": "object", "cardinality": "one", "typeName": "Report", "objectKind": "entity" }, args: { "id": "ID!", "title": "String!" } },
      "createAudit": { name: "createAudit", result: { "kind": "object", "cardinality": "one", "typeName": "AuditEvent", "objectKind": "entity" }, args: { "message": "String!" } },
    },
  },
  objects: {
    "Report": {
      type: "Report",
      kind: "entity",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "id": { name: "id", result: { "kind": "scalar", "cardinality": "one" } },
        "title": { name: "title", result: { "kind": "scalar", "cardinality": "one" } },
        "createdAt": { name: "createdAt", result: { "kind": "scalar", "cardinality": "one" } },
      },
    },
    "AuditEvent": {
      type: "AuditEvent",
      kind: "entity",
      fields: {
        "__typename": { name: "__typename", result: { "kind": "scalar", "cardinality": "one" } },
        "id": { name: "id", result: { "kind": "scalar", "cardinality": "one" } },
        "message": { name: "message", result: { "kind": "scalar", "cardinality": "one" } },
      },
    },
  },
};

// useQuery runtime entrypoint
export function useQuery(config?: GQLensQueryOptions): QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void } {
  const state = useGQLensSession({ ...config, schema: gqlensSchema });
  const ctx: AccessorContext = {
    root: "Query",
    store: state.store,
    demand: (steps) => state.demand("Query", steps),
    read: state.read,
  };
  const accessor = createAccessorNode<QueryNode>(ctx, gqlensSchema, gqlensSchema.query) as QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void };
  Object.defineProperties(accessor, {
    loading: { enumerable: true, get: () => state.loading },
    error: { enumerable: true, get: () => state.error },
    refetch: { enumerable: true, value: () => state.session.refetch() },
  });
  return accessor;
}

// useLiveQuery runtime entrypoint
export function useLiveQuery(config?: GQLensQueryOptions): QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void } {
  const state = useLiveGQLensSession({ ...config, schema: gqlensSchema });
  const ctx: AccessorContext = {
    root: "Query",
    store: state.store,
    demand: (steps) => state.demand("Query", steps),
    read: state.read,
  };
  const accessor = createAccessorNode<QueryNode>(ctx, gqlensSchema, gqlensSchema.query) as QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void };
  Object.defineProperties(accessor, {
    loading: { enumerable: true, get: () => state.loading },
    error: { enumerable: true, get: () => state.error },
    refetch: { enumerable: true, value: () => state.session.refetch() },
  });
  return accessor;
}

// usePreparedQuery prepared runtime entrypoint
export function usePreparedQuery(selection: PreparedSelection, variables: Readonly<Record<string, unknown>>, config?: GQLensQueryOptions): QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void } {
  const state = useGQLensSession({ ...config, schema: gqlensSchema });
  for (const path of bindGQLensSelection(selection, variables)) {
    state.demand(path.root, path.steps);
  }
  const ctx: AccessorContext = {
    root: "Query",
    store: state.store,
    demand: (steps) => state.demand("Query", steps),
    read: state.read,
  };
  const accessor = createAccessorNode<QueryNode>(ctx, gqlensSchema, gqlensSchema.query) as QueryNode & { readonly loading: boolean; readonly error: Error | null; readonly refetch: () => void };
  Object.defineProperties(accessor, {
    loading: { enumerable: true, get: () => state.loading },
    error: { enumerable: true, get: () => state.error },
    refetch: { enumerable: true, value: () => state.session.refetch() },
  });
  return accessor;
}

// Static selector builders
export function defineSelection(callback: (q: QueryNode, v: (name: string) => VariablePlaceholder) => void): PreparedSelection {
  return defineGQLensSelection<QueryNode>(gqlensSchema, gqlensSchema.query, callback);
}

export function defineInvalidation(callback: (q: QueryNode) => unknown): GraphDataInvalidation {
  return defineGQLensInvalidation<QueryNode>(gqlensSchema, gqlensSchema.query, callback);
}

// Mutation operation descriptors
export const api: {
  readonly audit: {
    readonly create: MutationOperation<Types.MutationCreateAuditArgs, Pick<NonNullable<Types.Mutation["createAudit"]>, "id" | "__typename" | "message">>;
  };
  readonly mutation: {
    readonly ping: MutationOperation<Record<string, unknown>, Types.Mutation["ping"]>;
    readonly rebuildIndex: MutationOperation<Record<string, unknown>, Types.Mutation["rebuildIndex"]>;
  };
  readonly report: {
    readonly rename: MutationOperation<Types.MutationRenameReportArgs, Pick<NonNullable<Types.Mutation["renameReport"]>, "id" | "__typename" | "title" | "createdAt">>;
  };
} = {
  audit: {
    create: {
      operationName: "createAudit",
      query: "mutation createAudit($message: String!) { createAudit(message: $message) { id __typename message } }",
      schema: gqlensSchema,
      variables: (input: Types.MutationCreateAuditArgs): Record<string, unknown> => ({
        message: input.message,
      }),
    },
  },
  mutation: {
    ping: {
      operationName: "ping",
      query: "mutation ping { ping }",
      schema: gqlensSchema,
      variables: (input: Record<string, unknown>): Record<string, unknown> => {
        void input;
        return {};
      },
    },
    rebuildIndex: {
      operationName: "rebuildIndex",
      query: "mutation rebuildIndex { rebuildIndex }",
      schema: gqlensSchema,
      variables: (input: Record<string, unknown>): Record<string, unknown> => {
        void input;
        return {};
      },
    },
  },
  report: {
    rename: {
      operationName: "renameReport",
      query: "mutation renameReport($id: ID!, $title: String!) { renameReport(id: $id, title: $title) { id __typename title createdAt } }",
      schema: gqlensSchema,
      variables: (input: Types.MutationRenameReportArgs): Record<string, unknown> => ({
        id: input.id,
        title: input.title,
      }),
    },
  },
};
