// Auto-generated by @gqlens/codegen
// Sections: typed nodes, schema metadata, runtime entrypoints, selectors, mutation API.
import { useGQLensSession, useLiveGQLensSession } from "@gqlens/react";
import {
  createAccessorNode,
  defineInvalidation as defineGQLensInvalidation,
  defineSelection as defineGQLensSelection,
  type AccessorContext,
  type SchemaMeta,
} from "@gqlens/core/codegen";
import type {
  InvalidationTarget,
  MutationOperation,
  PreparedSelection,
  QuerySessionConfig,
  VariablePlaceholder,
} from "@gqlens/core";
import type * as Types from "./types";

type GQLensArgValue<T> =
  T extends readonly (infer Item)[]
    ? readonly GQLensArgValue<Item>[] | VariablePlaceholder
    : T extends object
      ? { readonly [Key in keyof T]: GQLensArgValue<T[Key]> } | VariablePlaceholder
      : T | VariablePlaceholder;
type GQLensArgs<T> = { readonly [Key in keyof T]: GQLensArgValue<T[Key]> };

// Typed accessor nodes
export interface ReportNode {
  readonly __typename: string | undefined;
  readonly id: Types.Report["id"] | undefined;
  readonly title: Types.Report["title"] | undefined;
  readonly createdAt: Types.Report["createdAt"] | undefined;
}

export interface AuditEventNode {
  readonly __typename: string | undefined;
  readonly id: Types.AuditEvent["id"] | undefined;
  readonly message: Types.AuditEvent["message"] | undefined;
}

export interface QueryNode {
  readonly __typename: string | undefined;
  readonly reports: (args?: GQLensArgs<Types.QueryReportsArgs>) => { readonly ids: readonly string[] | undefined };
  readonly latestReport: ReportNode;
}

// Schema metadata consumed by @gqlens/core
const schemaMeta: SchemaMeta = {
  query: {
    type: "Query",
    identityKeys: ["id", "__typename"],
    fields: {
      "__typename": { name: "__typename", kind: "scalar" },
      "reports": { name: "reports", kind: "list", typeName: "Report", hasArgs: true },
      "latestReport": { name: "latestReport", kind: "entity", typeName: "Report" },
    },
  },
  planner: {
    roots: {
      "__typename": { returnsEntity: false },
      "reports": { returnsEntity: true, graphQLType: "Report", returnsList: true, args: { "filter": "SearchFilter", "ids": "[ID!]", "limit": "Int" } },
      "latestReport": { returnsEntity: true, graphQLType: "Report" },
    },
    types: {
      "Report": {
        "__typename": { returnsEntity: false },
        "id": { returnsEntity: false },
        "title": { returnsEntity: false },
        "createdAt": { returnsEntity: false },
      },
      "AuditEvent": {
        "__typename": { returnsEntity: false },
        "id": { returnsEntity: false },
        "message": { returnsEntity: false },
      },
      "Query": {
        "__typename": { returnsEntity: false },
        "reports": { returnsEntity: true, graphQLType: "Report", returnsList: true, args: { "filter": "SearchFilter", "ids": "[ID!]", "limit": "Int" } },
        "latestReport": { returnsEntity: true, graphQLType: "Report" },
      },
      "Mutation": {
        "__typename": { returnsEntity: false },
        "ping": { returnsEntity: false },
        "rebuildIndex": { returnsEntity: false },
        "renameReport": { returnsEntity: true, graphQLType: "Report", args: { "id": "ID!", "title": "String!" } },
        "createAudit": { returnsEntity: true, graphQLType: "AuditEvent", args: { "message": "String!" } },
      },
    },
  },
  entities: {
    "Report": {
      type: "Report",
      identityKeys: ["id", "__typename"],
      fields: {
        "__typename": { name: "__typename", kind: "scalar" },
        "id": { name: "id", kind: "scalar" },
        "title": { name: "title", kind: "scalar" },
        "createdAt": { name: "createdAt", kind: "scalar" },
      },
    },
    "AuditEvent": {
      type: "AuditEvent",
      identityKeys: ["id", "__typename"],
      fields: {
        "__typename": { name: "__typename", kind: "scalar" },
        "id": { name: "id", kind: "scalar" },
        "message": { name: "message", kind: "scalar" },
      },
    },
  },
};

// useQuery runtime entrypoint
export function useQuery(config?: Partial<Omit<QuerySessionConfig, "metadata">>): QueryNode & { readonly loading: boolean; readonly error: Error | null } {
  const state = useGQLensSession({ ...config, metadata: schemaMeta.planner });
  const ctx: AccessorContext = {
    root: "Query",
    cache: state.cache,
    demand: (steps) => state.demand("Query", steps),
    read: state.read,
  };
  const accessor = createAccessorNode<QueryNode>(ctx, schemaMeta, schemaMeta.query) as QueryNode & { readonly loading: boolean; readonly error: Error | null };
  Object.defineProperties(accessor, {
    loading: { enumerable: true, get: () => state.loading },
    error: { enumerable: true, get: () => state.error },
  });
  return accessor;
}

// useLiveQuery runtime entrypoint
export function useLiveQuery(config?: Partial<Omit<QuerySessionConfig, "metadata">>): QueryNode & { readonly loading: boolean; readonly error: Error | null } {
  const state = useLiveGQLensSession({ ...config, metadata: schemaMeta.planner });
  const ctx: AccessorContext = {
    root: "Query",
    cache: state.cache,
    demand: (steps) => state.demand("Query", steps),
    read: state.read,
  };
  const accessor = createAccessorNode<QueryNode>(ctx, schemaMeta, schemaMeta.query) as QueryNode & { readonly loading: boolean; readonly error: Error | null };
  Object.defineProperties(accessor, {
    loading: { enumerable: true, get: () => state.loading },
    error: { enumerable: true, get: () => state.error },
  });
  return accessor;
}

// Static selector builders
export function defineSelection(callback: (q: QueryNode, v: (name: string) => VariablePlaceholder) => void): PreparedSelection {
  return defineGQLensSelection<QueryNode>(schemaMeta, schemaMeta.query, callback);
}

export function defineInvalidation(callback: (q: QueryNode) => unknown): InvalidationTarget {
  return defineGQLensInvalidation<QueryNode>(schemaMeta, schemaMeta.query, callback);
}

// Mutation operation descriptors
export const api: {
  readonly audit: {
    readonly create: MutationOperation<Types.MutationCreateAuditArgs, Types.AuditEvent>;
  };
  readonly mutation: {
    readonly ping: MutationOperation<Record<string, unknown>, Types.Mutation["ping"]>;
    readonly rebuildIndex: MutationOperation<Record<string, unknown>, Types.Mutation["rebuildIndex"]>;
  };
  readonly report: {
    readonly rename: MutationOperation<Types.MutationRenameReportArgs, Types.Report>;
  };
} = {
  audit: {
    create: {
      operationName: "createAudit",
      query: "mutation createAudit($message: String!) { createAudit(message: $message) { id __typename message } }",
      variables: (input: Types.MutationCreateAuditArgs): Record<string, unknown> => ({
        message: input.message,
      }),
    },
  },
  mutation: {
    ping: {
      operationName: "ping",
      query: "mutation ping { ping }",
      variables: (input: Record<string, unknown>): Record<string, unknown> => {
        void input;
        return {};
      },
    },
    rebuildIndex: {
      operationName: "rebuildIndex",
      query: "mutation rebuildIndex { rebuildIndex }",
      variables: (input: Record<string, unknown>): Record<string, unknown> => {
        void input;
        return {};
      },
    },
  },
  report: {
    rename: {
      operationName: "renameReport",
      query: "mutation renameReport($id: ID!, $title: String!) { renameReport(id: $id, title: $title) { id __typename title createdAt } }",
      variables: (input: Types.MutationRenameReportArgs): Record<string, unknown> => ({
        id: input.id,
        title: input.title,
      }),
    },
  },
};

