// Auto-generated by @gqlens/codegen
import type { InvalidationTarget } from "@gqlens/core";

export type EntityInvalidationSpec = 
  | { readonly type: "Report"; readonly id: string; readonly keys?: readonly ("id" | "title" | "createdAt" | "id" | "__typename")[] }
  | { readonly type: "AuditEvent"; readonly id: string; readonly keys?: readonly ("id" | "message" | "id" | "__typename")[] }
;

export type InvalidationSpec = EntityInvalidationSpec | InvalidationTarget;
