// Auto-generated by @gqlens/codegen
import type { NormalizerEntry } from "@gqlens/core/codegen";

export const normalizerEntries: NormalizerEntry[] = [
  { type: "Report", fields: [
    { responseKey: "id", cacheKey: "id" },
    { responseKey: "title", cacheKey: "title" },
    { responseKey: "createdAt", cacheKey: "createdAt" },
  ] },
  { type: "AuditEvent", fields: [
    { responseKey: "id", cacheKey: "id" },
    { responseKey: "message", cacheKey: "message" },
  ] },
];
